import {RuntimeFault,requireThat} from './errors.js';
import {ansiEncode,ansiDecode} from './memory.js';
export function splitCommandLine(text){const args=[];let i=0;while(i<text.length){while(/\s/.test(text[i]||'')&&i<text.length)i++;if(i>=text.length)break;let s='',quote=false;while(i<text.length){if(!quote&&/\s/.test(text[i]))break;let slashes=0;while(text[i]==='\\'){slashes++;i++;}if(text[i]==='"'){s+='\\'.repeat(Math.floor(slashes/2));if(slashes%2){s+='"';i++;}else{if(quote&&text[i+1]==='"'){s+='"';i+=2;}else{quote=!quote;i++;}}}else{s+='\\'.repeat(slashes);if(i<text.length)s+=text[i++];}}args.push(s);while(i<text.length&&/\s/.test(text[i]))i++;}return args;}
export function installCRT(api){const p=api.p,m=api.m,v=api.vfs;const c=(name,n,fn)=>api.add('msvcrt.dll',name,n,fn,true);const ptr=s=>p.heap.string(s);const errno=p.heap.alloc(4,true);const error=n=>{m.w32(errno,n);return -1;};
  c('malloc',1,n=>p.heap.alloc(n));c('calloc',2,(n,size)=>{requireThat(n*size<=64*1024*1024,'HEAP_LIMIT','calloc size overflow or limit.');return p.heap.alloc(n*size,true);});c('realloc',2,(a,n)=>p.heap.realloc(a,n));c('free',1,a=>{if(!p.heap.free(a))throw new RuntimeFault('HEAP_POINTER','free received an invalid pointer.');return 0;});c('_msize',1,a=>p.heap.blocks.get(a)??0xFFFFFFFF);c('_errno',0,()=>errno);
  c('memcpy',3,(dst,src,n)=>{m.write(dst,m.read(src,n));return dst;});c('memmove',3,(dst,src,n)=>{m.write(dst,m.read(src,n));return dst;});c('memset',3,(dst,value,n)=>{m.fill(dst,n,value);return dst;});c('memcmp',3,(a,b,n)=>{requireThat(n<=m.limit,'MEMORY_LIMIT','memcmp length is excessive.');for(let i=0;i<n;i++){const d=m.u8(a+i)-m.u8(b+i);if(d)return d;}return 0;});c('memchr',3,(src,value,n)=>{for(let i=0;i<n;i++)if(m.u8(src+i)===(value&255))return src+i;return 0;});
  for(const wide of [false,true]){const read=a=>api.str(a,wide),prefix=wide?'wcs':'str',step=wide?2:1;
    c(prefix+'len',1,a=>read(a).length);c(prefix+'cpy',2,(a,b)=>{m.string(a,read(b),wide);return a;});c(prefix+'cat',2,(a,b)=>{m.string(a,read(a)+read(b),wide);return a;});
    c(prefix+'ncpy',3,(a,b,n)=>{const s=read(b);for(let i=0;i<n;i++){const value=i<s.length?s.charCodeAt(i):0;if(wide)m.w16(a+i*2,value);else m.w8(a+i,value);}return a;});
    c(prefix+'cmp',2,(a,b)=>{const x=read(a),y=read(b);return x===y?0:x<y?-1:1;});c(prefix+'ncmp',3,(a,b,n)=>{const x=read(a).slice(0,n),y=read(b).slice(0,n);return x===y?0:x<y?-1:1;});
    c('_'+prefix+'icmp',2,(a,b)=>{const x=read(a).toLowerCase(),y=read(b).toLowerCase();return x===y?0:x<y?-1:1;});
    c(prefix+'chr',2,(a,ch)=>{const s=read(a),i=ch===0?s.length:s.indexOf(String.fromCharCode(ch));return i<0?0:a+i*step;});c(prefix+'rchr',2,(a,ch)=>{const s=read(a),i=ch===0?s.length:s.lastIndexOf(String.fromCharCode(ch));return i<0?0:a+i*step;});
    c(prefix+'str',2,(a,b)=>{const i=read(a).indexOf(read(b));return i<0?0:a+i*step;});c('_'+prefix+'dup',1,a=>p.heap.string(read(a),wide));
  }
  c('atoi',1,a=>parseInt(m.cstr(a),10)||0);c('atol',1,a=>parseInt(m.cstr(a),10)||0);c('abs',1,n=>Math.abs(n|0));c('labs',1,n=>Math.abs(n|0));c('tolower',1,n=>n>=65&&n<=90?n+32:n);c('toupper',1,n=>n>=97&&n<=122?n-32:n);
  c('strtol',3,(text,end,base)=>{const s=m.cstr(text),radix=base||(/^[\s+-]*0x/i.test(s)?16:/^[\s+-]*0[0-9]/.test(s)?8:10);if(radix<2||radix>36){if(end)m.w32(end,text);return 0;}let i=0;while(/\s/.test(s[i]||'')&&i<s.length)i++;let sign=1;if(s[i]==='-'||s[i]==='+'){if(s[i]==='-')sign=-1;i++;}if(radix===16&&s.slice(i,i+2).toLowerCase()==='0x')i+=2;const start=i;let result=0;while(i<s.length){const digit=parseInt(s[i],36);if(!Number.isFinite(digit)||digit>=radix)break;result=result*radix+digit;i++;}if(end)m.w32(end,i===start?text:text+i);if(result*sign>2147483647||result*sign< -2147483648){m.w32(errno,34);return sign>0?2147483647:0x80000000;}return result*sign;});
  let rng=1;c('srand',1,seed=>{rng=seed;return 0;});c('rand',0,()=>{rng=(Math.imul(rng,214013)+2531011)>>>0;return (rng>>>16)&32767;});
  c('getenv',1,name=>{const value=p.environment.get(m.cstr(name).toUpperCase());return value===undefined?0:ptr(value);});c('_putenv',1,pointer=>{const text=m.cstr(pointer),i=text.indexOf('=');if(i<1)return -1;if(i===text.length-1)p.environment.delete(text.slice(0,i).toUpperCase());else p.environment.set(text.slice(0,i).toUpperCase(),text.slice(i+1));return 0;});
  const argv=splitCommandLine(p.commandLine);const argc=argv.length,argvArray=p.heap.alloc((argc+1)*4,true),wargvArray=p.heap.alloc((argc+1)*4,true);argv.forEach((s,i)=>{m.w32(argvArray+i*4,p.heap.string(s));m.w32(wargvArray+i*4,p.heap.string(s,true));});const argcP=p.heap.alloc(4),argvP=p.heap.alloc(4),wargvP=p.heap.alloc(4);m.w32(argcP,argc);m.w32(argvP,argvArray);m.w32(wargvP,wargvArray);
  const environment=[...p.environment].map(([k,val])=>k+'='+val),envArray=p.heap.alloc((environment.length+1)*4,true),envP=p.heap.alloc(4);environment.forEach((s,i)=>m.w32(envArray+i*4,ptr(s)));m.w32(envP,envArray);
  c('__getmainargs',5,(outc,outv,oute,wildcard,info)=>{m.w32(outc,argc);m.w32(outv,argvArray);m.w32(oute,envArray);return 0;});c('__p___argc',0,()=>argcP);c('__p___argv',0,()=>argvP);c('__p___wargv',0,()=>wargvP);c('__p__environ',0,()=>envP);c('__p__acmdln',0,()=>{const a=p.heap.alloc(4);m.w32(a,p.commandA);return a;});
  api.data('msvcrt.dll','__argc',argcP);api.data('msvcrt.dll','__argv',argvP);api.data('msvcrt.dll','_environ',envP);const acmdln=p.heap.alloc(4);m.w32(acmdln,p.commandA);api.data('msvcrt.dll','_acmdln',acmdln);
  const atExit=[];c('atexit',1,fn=>{atExit.push(fn);return 0;});c('_onexit',1,fn=>{atExit.push(fn);return fn;});
  c('exit',1,code=>{const next=()=>atExit.length?p.call(atExit.pop(),[],next):(p.exit(code),0);return next();});c('_exit',1,code=>{p.exit(code);return 0;});c('abort',0,()=>{throw new RuntimeFault('GUEST_ABORT','The guest C runtime called abort().');});
  c('_initterm',2,(first,last)=>{requireThat(last>=first&&last-first<=1024*1024,'CRT_INIT','Invalid initializer array.');let cursor=first;const next=()=>{while(cursor<last){const fn=m.u32(cursor);cursor+=4;if(fn)return p.call(fn,[],next);}return 0;};return next();});
  c('_initterm_e',2,(first,last)=>{requireThat(last>=first&&last-first<=1024*1024,'CRT_INIT','Invalid initializer array.');let cursor=first;const next=()=>{while(cursor<last){const fn=m.u32(cursor);cursor+=4;if(fn)return p.call(fn,[],value=>value||next());}return 0;};return next();});
  c('__set_app_type',1,type=>{p.applicationType=type;return 0;});let fmode=0x4000;c('_set_fmode',1,mode=>{fmode=mode;return 0;});c('_get_fmode',1,out=>{m.w32(out,fmode);return 0;});
  const readDouble=address=>new DataView(m.read(address,8).buffer).getFloat64(0,true);
  for(const [name,fn]of [['sin',Math.sin],['cos',Math.cos],['tan',Math.tan],['sqrt',Math.sqrt],['floor',Math.floor],['ceil',Math.ceil],['fabs',Math.abs],['exp',Math.exp],['log',Math.log],['log10',Math.log10],['atan',Math.atan]])c(name,2,()=>{p.cpu.fpush(fn(readDouble(p.apiStack+4)));return 0;});
  for(const [name,fn]of [['pow',Math.pow],['atan2',Math.atan2],['fmod',(a,b)=>a%b]])c(name,4,()=>{p.cpu.fpush(fn(readDouble(p.apiStack+4),readDouble(p.apiStack+12)));return 0;});
  c('_ftol',0,()=>{const n=BigInt(Math.trunc(p.cpu.fpop()));p.cpu.r[2]=Number(BigInt.asUintN(32,n>>32n));return Number(BigInt.asUintN(32,n));});
  const format=(fmt,argumentOffset,vaPointer=null)=>{
    let cursor=argumentOffset,va=vaPointer;const next=()=>{if(va!==null){const n=m.u32(va);va+=4;return n;}return p.apiArg(cursor++);};
    const nextDouble=()=>{const lo=next(),hi=next(),b=new ArrayBuffer(8),d=new DataView(b);d.setUint32(0,lo,true);d.setUint32(4,hi,true);return d.getFloat64(0,true);};
    let output='';for(let i=0;i<fmt.length;i++){if(fmt[i]!=='%'){output+=fmt[i];continue;}if(fmt[i+1]==='%'){output+='%';i++;continue;}
      let flags='';while('-+ #0'.includes(fmt[i+1]||'\0'))flags+=fmt[++i];let width='';while(/[0-9]/.test(fmt[i+1]||''))width+=fmt[++i];let minWidth=Number(width)||0;if(fmt[i+1]==='*'){minWidth=next()|0;i++;if(minWidth<0){flags+='-';minWidth=-minWidth;}}
      let precision=null;if(fmt[i+1]==='.'){i++;let digits='';while(/[0-9]/.test(fmt[i+1]||''))digits+=fmt[++i];precision=Number(digits)||0;if(fmt[i+1]==='*'){precision=next()|0;i++;if(precision<0)precision=null;}}
      let length='';if(fmt.slice(i+1,i+4)==='I64'){length='ll';i+=3;}else while(['h','l','L','z','t'].includes(fmt[i+1]))length+=fmt[++i];
      const type=fmt[++i];requireThat(minWidth<=65536&&(precision===null||precision<=65536),'CRT_FORMAT','Formatting width/precision exceeds limits.');let text='';
      if(type==='s'){const address=next();text=address?(length==='l'?m.wstr(address):m.cstr(address)):'(null)';if(precision!==null)text=text.slice(0,precision);}
      else if(type==='c')text=String.fromCharCode(next()&65535);
      else if('diuxXop'.includes(type||'\0')){const lo=next();let n=length==='ll'?((BigInt(next())<<32n)|BigInt(lo)):BigInt(lo);if(type==='d'||type==='i')n=BigInt.asIntN(length==='ll'?64:32,n);const radix=type==='x'||type==='X'||type==='p'?16:type==='o'?8:10;text=n.toString(radix);if(type==='X')text=text.toUpperCase();if(type==='p')text=text.padStart(8,'0');if(precision!==null)text=text.startsWith('-')?'-'+text.slice(1).padStart(precision,'0'):text.padStart(precision,'0');if(flags.includes('#')&&n!==0n)text=(radix===16?(type==='X'?'0X':'0x'):radix===8?'0':'')+text;if(n>=0n&&(type==='d'||type==='i')){if(flags.includes('+'))text='+'+text;else if(flags.includes(' '))text=' '+text;}}
      else if('fFeEgG'.includes(type||'\0')){const n=nextDouble(),pr=precision??6;requireThat(pr<=100,'CRT_FORMAT','Floating precision exceeds the implementation limit.');text=type.toLowerCase()==='f'?n.toFixed(pr):type.toLowerCase()==='e'?n.toExponential(pr):n.toPrecision(Math.max(1,pr));if(type===type.toUpperCase())text=text.toUpperCase();if(n>=0&&flags.includes('+'))text='+'+text;}
      else if(type==='n'){const address=next();if(length==='h')m.w16(address,output.length);else m.w32(address,output.length);continue;}
      else throw new RuntimeFault('CRT_FORMAT',`printf format %${length}${type} is not implemented.`);
      if(flags.includes('-'))text=text.padEnd(minWidth,' ');else if(flags.includes('0')&&precision===null&&/^[+-]/.test(text))text=text[0]+text.slice(1).padStart(Math.max(0,minWidth-1),'0');else text=text.padStart(minWidth,flags.includes('0')&&precision===null?'0':' ');output+=text;requireThat(output.length<=1024*1024,'CRT_FORMAT','Formatted output exceeds 1 MiB.');}
    return output;
  };
  c('printf',1,fmt=>{const text=format(m.cstr(fmt),1);p.emit('stdout',{text,stream:'stdout'});return text.length;});c('vprintf',2,(fmt,args)=>{const text=format(m.cstr(fmt),0,args);p.emit('stdout',{text,stream:'stdout'});return text.length;});c('sprintf',2,(out,fmt)=>{const text=format(m.cstr(fmt),2);m.string(out,text);return text.length;});
  c('snprintf',3,(out,count,fmt)=>{const text=format(m.cstr(fmt),3);if(count)m.string(out,text,false,count);return text.length;});c('_snprintf',3,(out,count,fmt)=>{const text=format(m.cstr(fmt),3);if(count){const bytes=ansiEncode(text);m.write(out,bytes.subarray(0,count));if(bytes.length<count)m.w8(out+bytes.length,0);}return text.length>=count?-1:text.length;});
  api.add('user32.dll','wsprintfA',2,(out,fmt)=>{const text=format(m.cstr(fmt),2);requireThat(text.length<1024,'CRT_FORMAT','wsprintf output exceeds 1024 bytes.');m.string(out,text);return text.length;},true);
  c('puts',1,text=>{p.emit('stdout',{text:m.cstr(text)+'\n',stream:'stdout'});return 0;});c('putchar',1,ch=>{p.emit('stdout',{text:String.fromCharCode(ch&255),stream:'stdout'});return ch&255;});
  c('_write',3,(fd,buffer,count)=>{if(fd!==1&&fd!==2)return error(9);p.emit('stdout',{text:ansiDecode(m.read(buffer,count)),stream:fd===2?'stderr':'stdout'});return count;});
  const streams=new Map();const streamError=n=>{m.w32(errno,n);return 0;};
  c('fopen',2,(filename,modePtr)=>{const mode=m.cstr(modePtr),name=m.cstr(filename);if(!/^[rwa][+bt]*$/.test(mode))return streamError(22);return api.expected(()=>{const path=v.path(name),exists=v.exists(path);if(mode[0]==='r'&&!exists)return streamError(2);if(mode[0]==='w'||!exists)v.writeFile(path,new Uint8Array());const handle=p.heap.alloc(64,true);streams.set(handle,{path,position:mode[0]==='a'?v.readFile(path).length:0,read:mode[0]==='r'||mode.includes('+'),write:mode[0]!=='r'||mode.includes('+'),append:mode[0]==='a',eof:false});return handle;});});
  c('fclose',1,h=>{if(!streams.has(h))return -1;streams.delete(h);p.heap.free(h);return 0;});
  c('fread',4,(out,size,count,h)=>{const f=streams.get(h);if(!f?.read)return 0;const n=size*count;requireThat(n<=128*1024*1024,'CRT_IO','fread size exceeds limits.');if(!size)return 0;const data=v.readFile(f.path).subarray(f.position,f.position+n);m.write(out,data);f.position+=data.length;f.eof=data.length<n;return Math.floor(data.length/size);});
  c('fwrite',4,(data,size,count,h)=>{const f=streams.get(h);if(!f?.write||!size)return 0;const n=size*count;requireThat(n<=128*1024*1024,'CRT_IO','fwrite size exceeds limits.');if(f.append)f.position=v.readFile(f.path).length;v.writeAt(f.path,f.position,m.read(data,n));f.position+=n;return count;});
  c('fflush',1,h=>!h||streams.has(h)?0:-1);c('feof',1,h=>streams.get(h)?.eof?1:0);c('ftell',1,h=>streams.get(h)?.position??-1);
  c('fseek',3,(h,offset,origin)=>{const f=streams.get(h);if(!f)return -1;const base=origin===0?0:origin===1?f.position:origin===2?v.readFile(f.path).length:-1;if(base<0||base+(offset|0)<0)return -1;f.position=base+(offset|0);f.eof=false;return 0;});
  c('fputc',2,(ch,h)=>{const f=streams.get(h);if(!f?.write)return -1;v.writeAt(f.path,f.position,Uint8Array.of(ch&255));f.position++;return ch&255;});c('fgetc',1,h=>{const f=streams.get(h);if(!f?.read)return -1;const data=v.readFile(f.path);if(f.position>=data.length){f.eof=true;return -1;}return data[f.position++];});
  c('fprintf',2,(h,fmt)=>{const f=streams.get(h);if(!f?.write)return -1;const text=format(m.cstr(fmt),2),data=ansiEncode(text);v.writeAt(f.path,f.position,data);f.position+=data.length;return data.length;});
  c('remove',1,name=>api.expected(()=>v.remove(m.cstr(name))?0:-1,-1));c('rename',2,(from,to)=>api.expected(()=>v.rename(m.cstr(from),m.cstr(to))?0:-1,-1));
  c('time',1,out=>{const seconds=Math.floor(Date.now()/1000);if(out)m.w32(out,seconds);return seconds;});c('clock',0,()=>Math.floor(performance.now()-p.started));
}
