import {requireThat} from './errors.js';

export function installMenus(gui){
  const api=gui.api,p=gui.p,m=gui.m,u=(n,a,f)=>api.add('user32.dll',n,a,f),get=h=>p.object(h,'menu');
  const create=items=>p.handle('menu',{items});
  const containsMenu=(root,target)=>{const pending=[root],seen=new Set();while(pending.length){const h=pending.pop();if(h===target)return true;if(seen.has(h))continue;seen.add(h);for(const item of get(h)?.items||[])if(item.submenu)pending.push(item.submenu);}return false;};
  const find=(handle,id,position)=>{const menu=get(handle);if(!menu)return null;if(position)return menu.items[id]?{menu,index:id,item:menu.items[id]}:null;for(let index=0;index<menu.items.length;index++){const item=menu.items[index];if(item.id===id)return {menu,index,item};if(item.submenu){const nested=find(item.submenu,id,false);if(nested)return nested;}}return null;};
  gui.serializeMenu=handle=>{const menu=get(handle);return menu?{handle,items:menu.items.map(item=>({...item,submenu:item.submenu?gui.serializeMenu(item.submenu):null}))}:null;};
  const notify=()=>{for(const w of gui.windows.values())if(w.menu)gui.notify(w);};
  const label=text=>text.replace(/&&/g,'\0').replace(/&/g,'').replace(/\0/g,'&');
  const layout=w=>{let x=0;const hits=[];for(const item of get(w.menu)?.items||[]){const width=label(item.text).length*7+18;hits.push({item,x,y:0,width,height:22,level:0});x+=width;}for(const [index,popup]of (w.menuPath||[]).entries()){const items=get(popup.handle)?.items||[],width=Math.max(140,...items.map(i=>label(i.text).length*7+34));let y=popup.y;for(const item of items){const height=item.flags&0x800?6:22;hits.push({item,x:popup.x,y,width,height,level:index+1});y+=height;}}return hits;};
  gui.paintMenu=w=>{if(!w.menu)return;const draw=command=>gui.draw(w.dc,{...command,surface:'nonclient'});draw({op:'fill',x:0,y:0,width:w.width,height:22,color:0xf0f0f0});for(const hit of layout(w)){const {item,x,y,width,height}=hit;if(hit.level)draw({op:'rectangle',x,y,width,height,pen:{color:0xc0c0c0,width:1},brush:{color:0xf0f0f0}});if(item.flags&0x800){draw({op:'line',x:x+4,y:y+3,x2:x+width-4,y2:y+3,pen:{color:0x888888,width:1}});continue;}draw({op:'text',x:x+8,y:y+4,text:(hit.level&&item.flags&8?'\u2713 ':'')+label(item.text)+(hit.level&&item.submenu?'  >':''),color:item.flags&3?0x888888:0,font:{height:13,face:'Arial',weight:400},align:0});}};
  gui.menuMouse=(w,event)=>{const x=event.x,y=event.y+22,hit=layout(w).reverse().find(h=>x>=h.x&&x<h.x+h.width&&y>=h.y&&y<h.y+h.height);if(!hit){if(w.menuPath?.length&&event.event==='down'){w.menuPath=[];gui.paintMenu(w);gui.queuePaint(w);return true;}return y<22;}if(event.event!=='down')return true;const {item}=hit;if(item.flags&0x803)return true;if(item.submenu){w.menuPath=(w.menuPath||[]).slice(0,hit.level);w.menuPath.push({handle:item.submenu,x:hit.level?hit.x+hit.width:hit.x,y:hit.level?hit.y:22});gui.menuInput({kind:'menu-open',hwnd:w.hwnd,menu:item.submenu});gui.paintMenu(w);}else{gui.menuInput({kind:'menu',hwnd:w.hwnd,id:item.id});w.menuPath=[];gui.paintMenu(w);gui.queuePaint(w);}return true;};
  gui.loadMenu=(instance,name)=>{
    const module=api.module(instance);if(!module)return api.fail(6);const resource=p.loader.resource(module,4,name);if(!resource)return api.fail(1814);
    let cursor=resource.address;const end=cursor+resource.size,word=()=>{requireThat(cursor+2<=end,'MENU_RESOURCE','Truncated menu resource.');const value=m.u16(cursor);cursor+=2;return value;};
    requireThat(word()===0,'MENU_RESOURCE','Extended menu resource templates are not implemented.');const offset=word();cursor+=offset;let total=0;
    const list=depth=>{requireThat(depth<32,'MENU_RESOURCE','Menu nesting limit exceeded.');const items=[];let flags;do{requireThat(++total<=4096,'MENU_RESOURCE','Menu item limit exceeded.');flags=word();const popup=!!(flags&16),id=popup?0:word();let text='',ch;while((ch=word()))text+=String.fromCharCode(ch);const submenu=popup?list(depth+1):0;items.push({id,flags:flags&~0x80,text,submenu});}while(!(flags&0x80));return create(items);};
    return list(0);
  };
  for(const wide of [false,true]){
    const suffix=wide?'W':'A';u('LoadMenu'+suffix,2,(instance,name)=>gui.loadMenu(instance,name<65536?name:api.str(name,wide)));
    u('AppendMenu'+suffix,4,(handle,flags,id,text)=>{const menu=get(handle);if(!menu)return api.fail(1401);requireThat(!(flags&0x104),'UNSUPPORTED_MENU','Bitmap and owner-drawn menu items are not implemented.');if(flags&16&&(!get(id)||containsMenu(id,handle)))return api.fail(1401);menu.items.push({id:flags&16?0:id,flags,text:flags&0x800?'':api.str(text,wide),submenu:flags&16?id:0});notify();return 1;});
    u('GetMenuItemInfo'+suffix,4,(handle,id,position,out)=>{const found=find(handle,id,position);if(!found||!out)return api.fail(87);const size=m.u32(out),mask=m.u32(out+4),item=found.item;if(size!==44&&size!==48)return api.fail(87);if(mask&1)m.w32(out+12,item.flags&0xb);if(mask&2)m.w32(out+16,item.id);if(mask&4)m.w32(out+20,item.submenu);if(mask&0x100)m.w32(out+8,item.flags&0x900);if(mask&0x20)m.w32(out+32,0);if(mask&0x40||mask&0x10){if(mask&0x10)m.w32(out+8,item.flags&0x900);const buffer=m.u32(out+36),count=m.u32(out+40);if(buffer&&count){m.string(buffer,item.text,wide,count);m.w32(out+40,Math.min(item.text.length,count-1));}else m.w32(out+40,item.text.length);}return 1;});
  }
  u('SetMenu',2,(hwnd,handle)=>{const w=gui.window(hwnd);if(!w)return api.fail(1400);if(w.style&0x40000000)return api.fail(87);if(handle&&!get(handle))return api.fail(1401);w.menu=handle;w.menuPath=[];gui.notify(w);if(w.visible)gui.queuePaint(w);return 1;});
  u('DrawMenuBar',1,hwnd=>{const w=gui.window(hwnd);if(!w)return api.fail(1400);gui.paintMenu(w);return 1;});
  u('CreateMenu',0,()=>create([]));u('CreatePopupMenu',0,()=>create([]));u('GetMenu',1,hwnd=>gui.window(hwnd)?.menu||0);
  u('GetSubMenu',2,(handle,index)=>get(handle)?.items[index]?.submenu||0);u('GetMenuItemCount',1,handle=>get(handle)?.items.length??-1);
  const destroy=handle=>{const pending=[handle],seen=new Set();while(pending.length){const h=pending.pop();if(seen.has(h))continue;seen.add(h);for(const item of get(h)?.items||[])if(item.submenu)pending.push(item.submenu);p.releaseHandle(h);}};
  u('DestroyMenu',1,handle=>{if(!get(handle))return api.fail(1401);destroy(handle);notify();return 1;});
  u('DeleteMenu',3,(handle,id,flags)=>{if(!get(handle))return api.fail(1401);const found=find(handle,id,flags&0x400);if(!found)return api.fail(1456);found.menu.items.splice(found.index,1);if(found.item.submenu)destroy(found.item.submenu);notify();return 1;});
  u('RemoveMenu',3,(handle,id,flags)=>{const found=find(handle,id,flags&0x400);if(!found)return api.fail(1456);found.menu.items.splice(found.index,1);notify();return 1;});
  for(const [name,bits]of [['CheckMenuItem',8],['EnableMenuItem',3]])u(name,3,(handle,id,flags)=>{const found=find(handle,id,flags&0x400);if(!found)return 0xffffffff;const previous=found.item.flags&bits;found.item.flags=(found.item.flags&~bits)|(flags&bits);notify();return previous;});
  gui.menuInput=event=>{const w=gui.window(event.hwnd);if(!w?.menu)return;if(event.kind==='menu-open'){if(!containsMenu(w.menu,event.menu))return;p.postMessage(w.hwnd,0x116,w.menu,0);p.postMessage(w.hwnd,0x117,event.menu,0);return;}const found=find(w.menu,event.id,false);if(found&&!found.item.submenu&&!(found.item.flags&0x803))p.postMessage(w.hwnd,0x111,event.id&0xffff,0);};
}
