#include "minwin.h"
unsigned long __readfsdword(unsigned long);
#pragma intrinsic(__readfsdword)
#define CHECK(expression) do { if(!(expression)) { printf("Handle failure at line %d\n",__LINE__); ExitProcess(__LINE__); } } while(0)
static DWORD initializationCalls;
static BOOL WINAPI initializeOnce(DWORD *once,void *parameter,void **context){
  initializationCalls++;if(initializationCalls==1){SetLastError(123);return 0;}
  *context=parameter;return 1;
}
void mainCRTStartup(void){
  HANDLE self=GetCurrentProcess(),file,copy,process,thread;
  DWORD flags,count,code;
  char bytes[4];
  char finalPath[256];
  WORD finalWide[256];
  long long position;
  long long endOfFile;
  FILETIME creation={123,30000000},access={456,30000001},write={789,30000002},returned;
  BY_HANDLE_FILE_INFORMATION info;
  FILE_STANDARD_INFO standard;
  FILE_ID_INFO identity;
  FILE_ATTRIBUTE_TAG_INFO tag;
  FILE_NAME_BUFFER filename;
  FILE_RENAME_BUFFER rename;
  DWORD originalId;
  DWORD tls[65],index;
  DWORD once=0,manual=0;BOOL pending;void *onceContext=NULL;
  CRITICAL_SECTION critical;
  BYTE disposition;
  const WORD wideFile[]={'h','a','n','d','l','e','s','.','t','x','t',0};
  file=CreateFileA("handles.txt",GENERIC_READ|GENERIC_WRITE,0,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(GetFileInformationByHandle(file,&info));originalId=info.idLow;
  CHECK(DuplicateHandle(self,file,self,&copy,0,1,2));
  CHECK(copy!=file);
  CHECK(GetHandleInformation(copy,&flags)&&flags==1);
  CHECK(SetHandleInformation(file,2,2));
  CHECK(!CloseHandle(file)&&GetLastError()==6);
  CHECK(WriteFile(file,"ab",2,&count,NULL)&&count==2);
  CHECK(WriteFile(copy,"cd",2,&count,NULL)&&count==2);
  CHECK(SetFilePointer(copy,0,NULL,0)==0);
  CHECK(ReadFile(file,bytes,2,&count,NULL)&&count==2&&bytes[0]=='a'&&bytes[1]=='b');
  CHECK(SetHandleInformation(file,2,0)&&CloseHandle(file));
  CHECK(ReadFile(copy,bytes,2,&count,NULL)&&count==2&&bytes[0]=='c'&&bytes[1]=='d');
  CHECK(SetFilePointerEx(copy,0x20000000000003LL,&position,0)&&position==0x20000000000003LL);
  CHECK(WriteFile(copy,NULL,0,&count,NULL)&&count==0);
  CHECK(ReadFile(copy,bytes,1,&count,NULL)&&count==0);
  CHECK(GetFileSizeEx(copy,&position)&&position==4);
  CHECK(!WriteFile(copy,"x",1,&count,NULL)&&GetLastError()==112);
  CHECK(SetFilePointerEx(copy,-1,&position,1)&&position==0x20000000000002LL);
  CHECK(SetFilePointerEx(copy,-2,&position,2)&&position==2);
  CHECK(SetEndOfFile(copy));
  CHECK(GetFileSizeEx(copy,&position)&&position==2);
  endOfFile=8;
  CHECK(SetFileInformationByHandle(copy,6,&endOfFile,sizeof(endOfFile)));
  CHECK(GetFileSizeEx(copy,&position)&&position==8);
  CHECK(SetFilePointerEx(copy,0,&position,1)&&position==2);
  endOfFile=-1;
  CHECK(!SetFileInformationByHandle(copy,6,&endOfFile,sizeof(endOfFile))&&GetLastError()==87);
  endOfFile=2;
  CHECK(SetFileInformationByHandle(copy,6,&endOfFile,sizeof(endOfFile)));
  CHECK(SetFileTime(copy,&creation,&access,&write));
  CHECK(GetFileTime(copy,NULL,NULL,&returned)&&returned.low==789&&returned.high==30000002);
  CHECK(GetFileInformationByHandle(copy,&info)&&info.idLow==originalId&&info.sizeLow==2&&info.links==1);
  CHECK(info.creation.low==123&&info.access.low==456&&info.write.low==789);
  CHECK(SetFileAttributesA("handles.txt",3)&&GetFileAttributesA("handles.txt")==3);
  CHECK(SetFileAttributesW(wideFile,128)&&GetFileAttributesA("handles.txt")==128);
  CHECK(sizeof(standard)==24&&sizeof(identity)==24&&sizeof(tag)==8);
  CHECK(GetFileInformationByHandleEx(copy,1,&standard,sizeof(standard)));
  CHECK(standard.endOfFile==2&&standard.allocationSize==2&&standard.links==1&&!standard.deletePending&&!standard.directory);
  CHECK(GetFileInformationByHandleEx(copy,18,&identity,sizeof(identity)));
  CHECK(identity.volume==0xB8600001ULL&&*(DWORD*)identity.id==originalId);
  CHECK(GetFileInformationByHandleEx(copy,9,&tag,sizeof(tag))&&tag.attributes==128&&tag.reparseTag==0);
  CHECK(GetFileInformationByHandleEx(copy,2,&filename,sizeof(filename))&&filename.name[0]=='\\');
  CHECK(!GetFileInformationByHandleEx(copy,2,&filename,8)&&GetLastError()==234&&filename.length>4);
  CHECK(CloseHandle(copy));
  file=CreateFileA("handles.txt",GENERIC_READ,7,NULL,3,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  count=GetFinalPathNameByHandleW(file,NULL,0,0);
  CHECK(count>5&&count<256&&GetFinalPathNameByHandleW(file,finalWide,256,0)==count-1);
  CHECK(finalWide[0]=='\\'&&finalWide[1]=='\\'&&finalWide[2]=='?'&&finalWide[3]=='\\');
  CHECK(GetFinalPathNameByHandleA(file,finalPath,256,8)>0);
  copy=CreateFileA(finalPath,GENERIC_READ,7,NULL,3,0,NULL);
  CHECK(copy!=INVALID_HANDLE&&CloseHandle(copy)&&CloseHandle(file));
  /* A deleted name stays reserved until the last open file object closes. */
  file=CreateFileA("pending.txt",GENERIC_READ|GENERIC_WRITE,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(WriteFile(file,"xy",2,&count,NULL)&&count==2);
  CHECK(DuplicateHandle(self,file,self,&copy,0,0,2));
  CHECK(DeleteFileA("pending.txt"));
  CHECK(GetFileInformationByHandleEx(copy,1,&standard,sizeof(standard))&&standard.deletePending&&standard.links==0);
  CHECK(CreateFileA("pending.txt",GENERIC_READ,7,NULL,2,0,NULL)==INVALID_HANDLE&&GetLastError()==5);
  CHECK(CloseHandle(file));
  CHECK(SetFilePointer(copy,0,NULL,0)==0);
  CHECK(ReadFile(copy,bytes,2,&count,NULL)&&count==2&&bytes[0]=='x'&&bytes[1]=='y');
  CHECK(CloseHandle(copy));
  CHECK(CreateFileA("pending.txt",GENERIC_READ,7,NULL,3,0,NULL)==INVALID_HANDLE&&GetLastError()==2);
  file=CreateFileA("temporary.txt",GENERIC_READ|GENERIC_WRITE,7,NULL,2,0x04000000,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(DuplicateHandle(self,file,self,&copy,0,0,3));
  CHECK(WriteFile(copy,"z",1,&count,NULL)&&count==1);
  CHECK(CloseHandle(copy));
  CHECK(CreateFileA("temporary.txt",GENERIC_READ,7,NULL,3,0,NULL)==INVALID_HANDLE&&GetLastError()==2);
  file=CreateFileA("disposition.txt",GENERIC_READ|GENERIC_WRITE|0x10000,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(DuplicateHandle(self,file,self,&copy,0,0,2));
  disposition=1;CHECK(SetFileInformationByHandle(file,4,&disposition,1));
  CHECK(GetFileInformationByHandleEx(copy,1,&standard,sizeof(standard))&&standard.deletePending&&standard.links==0);
  disposition=0;CHECK(SetFileInformationByHandle(copy,4,&disposition,1));
  CHECK(GetFileInformationByHandleEx(file,1,&standard,sizeof(standard))&&!standard.deletePending&&standard.links==1);
  disposition=1;CHECK(SetFileInformationByHandle(copy,4,&disposition,1));
  CHECK(CloseHandle(file)&&CloseHandle(copy));
  CHECK(CreateFileA("disposition.txt",GENERIC_READ,7,NULL,3,0,NULL)==INVALID_HANDLE&&GetLastError()==2);
  file=CreateFileA("rename-source.txt",GENERIC_READ|GENERIC_WRITE|0x10000,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(GetFileInformationByHandle(file,&info));originalId=info.idLow;
  memset(&rename,0,sizeof(rename));rename.length=10;
  rename.name[0]='r';rename.name[1]='.';rename.name[2]='t';rename.name[3]='x';rename.name[4]='t';
  CHECK((char*)rename.name-(char*)&rename==12);
  CHECK(SetFileInformationByHandle(file,3,&rename,sizeof(rename)));
  CHECK(GetFileInformationByHandle(file,&info)&&info.idLow==originalId);
  CHECK(CreateFileA("rename-source.txt",GENERIC_READ,7,NULL,3,0,NULL)==INVALID_HANDLE&&GetLastError()==2);
  CHECK(WriteFile(file,"r",1,&count,NULL)&&count==1);
  CHECK(CloseHandle(file)&&DeleteFileA("r.txt"));
  CHECK(CreateDirectoryA("rename-dir",NULL));
  file=CreateFileA("rename-dir/child",GENERIC_WRITE,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE&&WriteFile(file,"d",1,&count,NULL)&&CloseHandle(file));
  file=CreateFileA("rename-dir",0x10000,7,NULL,3,0x02000000,NULL);
  CHECK(file!=INVALID_HANDLE&&SetFileInformationByHandle(file,3,&rename,sizeof(rename)));
  CHECK(CloseHandle(file)&&MoveFileA("r.txt","rename-dir"));
  file=CreateFileA("rename-dir/child",GENERIC_READ,7,NULL,3,0,NULL);
  CHECK(file!=INVALID_HANDLE&&ReadFile(file,bytes,1,&count,NULL)&&count==1&&bytes[0]=='d');
  CHECK(CloseHandle(file)&&DeleteFileA("rename-dir/child")&&RemoveDirectoryA("rename-dir"));
  file=CreateFileA("append.txt",4,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE&&WriteFile(file,"ab",2,&count,NULL)&&count==2);
  CHECK(SetFilePointer(file,0,NULL,0)==0);
  CHECK(WriteFile(file,"c",1,&count,NULL)&&count==1);
  CHECK(SetFilePointerEx(file,0,&position,1)&&position==3);
  CHECK(!SetEndOfFile(file)&&GetLastError()==5);
  CHECK(CloseHandle(file));
  file=CreateFileA("append.txt",GENERIC_READ,7,NULL,3,0,NULL);
  CHECK(file!=INVALID_HANDLE&&ReadFile(file,bytes,3,&count,NULL)&&count==3);
  CHECK(bytes[0]=='a'&&bytes[1]=='b'&&bytes[2]=='c');
  CHECK(CloseHandle(file)&&DeleteFileA("append.txt"));
  CHECK(GetTempFileNameA("C:\\Temp","b86",0,finalPath)!=0);
  file=CreateFileA(finalPath,GENERIC_READ,7,NULL,3,0,NULL);
  CHECK(file!=INVALID_HANDLE&&GetFileSizeEx(file,&position)&&position==0);
  CHECK(CloseHandle(file)&&DeleteFileA(finalPath));
  finalWide[0]='.';finalWide[1]=0;rename.name[0]='t';rename.name[1]='m';rename.name[2]='p';rename.name[3]=0;
  CHECK(GetTempFileNameW(finalWide,rename.name,0x12345,filename.name)==0x2345);
  for(index=0;index<65;index++){tls[index]=TlsAlloc();CHECK(tls[index]!=0xFFFFFFFF);CHECK(TlsGetValue(tls[index])==NULL);}
  CHECK(TlsSetValue(tls[64],(void*)0xFEDCBA98));
  CHECK(*(DWORD*)(__readfsdword(0xF94)+(tls[64]-64)*4)==0xFEDCBA98);
  CHECK(TlsSetValue(tls[0],(void*)0x12345678));
  CHECK(*(DWORD*)(__readfsdword(0x18)+0xE10+tls[0]*4)==0x12345678);
  SetLastError(123);CHECK(TlsGetValue2(tls[64])==(void*)0xFEDCBA98&&GetLastError()==123);
  CHECK(TlsGetValue(tls[64])==(void*)0xFEDCBA98&&GetLastError()==0);
  CHECK(TlsFree(tls[12]));index=TlsAlloc();CHECK(index==tls[12]&&TlsGetValue(index)==NULL);
  for(index=0;index<65;index++)CHECK(TlsFree(tls[index]));
  CHECK(!InitOnceExecuteOnce(&once,initializeOnce,(void*)0x123400,&onceContext)&&GetLastError()==123);
  CHECK(InitOnceExecuteOnce(&once,initializeOnce,(void*)0x123400,&onceContext)&&onceContext==(void*)0x123400);
  CHECK(InitOnceExecuteOnce(&once,initializeOnce,NULL,&onceContext)&&initializationCalls==2);
  InitOnceInitialize(&manual);
  CHECK(InitOnceBeginInitialize(&manual,0,&pending,&onceContext)&&pending);
  CHECK(InitOnceComplete(&manual,0,(void*)0x567800));
  CHECK(InitOnceBeginInitialize(&manual,1,&pending,&onceContext)&&!pending&&onceContext==(void*)0x567800);
  index=0;flags=1;CHECK(WaitOnAddress(&index,&flags,4,0));
  flags=0;CHECK(!WaitOnAddress(&index,&flags,4,0)&&GetLastError()==1460);
  CHECK(!WaitOnAddress(&index,&flags,3,0)&&GetLastError()==87);
  WakeByAddressSingle(&index);WakeByAddressAll(&index);
  CHECK(sizeof(critical)==24&&InitializeCriticalSectionEx(&critical,4000,0x01000000));
  CHECK(critical.lockCount==-1&&critical.recursion==0&&critical.spin==0);
  EnterCriticalSection(&critical);CHECK(TryEnterCriticalSection(&critical));
  CHECK(critical.recursion==2&&critical.owner==(HANDLE)8&&critical.lockCount==-2);
  CHECK(SetCriticalSectionSpinCount(&critical,200)==0);
  LeaveCriticalSection(&critical);LeaveCriticalSection(&critical);
  CHECK(critical.recursion==0&&critical.owner==NULL&&critical.lockCount==-1);
  DeleteCriticalSection(&critical);InitializeCriticalSection(&critical);DeleteCriticalSection(&critical);
  CHECK(InitializeCriticalSectionAndSpinCount(&critical,100));DeleteCriticalSection(&critical);
  CHECK(SetEnvironmentVariableA("B86_TEST","value"));
  DWORD srw=0;
  AcquireSRWLockShared(&srw);CHECK(!TryAcquireSRWLockExclusive(&srw));ReleaseSRWLockShared(&srw);
  AcquireSRWLockExclusive(&srw);CHECK(!TryAcquireSRWLockShared(&srw));CHECK(!TryAcquireSRWLockExclusive(&srw));ReleaseSRWLockExclusive(&srw);
  InitializeSRWLock(&srw);CHECK(TryAcquireSRWLockShared(&srw));ReleaseSRWLockShared(&srw);
  CHECK(TryAcquireSRWLockExclusive(&srw));ReleaseSRWLockExclusive(&srw);
  DWORD condition=0;
  SYSTEMTIME utc={2000,2,65535,29,23,59,59,999},converted;FILETIME stamp,epoch={0,0};
  CHECK(SystemTimeToFileTime(&utc,&stamp));CHECK(FileTimeToSystemTime(&stamp,&converted));
  CHECK(converted.year==2000&&converted.month==2&&converted.day==29&&converted.weekday==2&&converted.millis==999);
  CHECK(CompareFileTime(&epoch,&stamp)==-1&&CompareFileTime(&stamp,&epoch)==1&&CompareFileTime(&stamp,&stamp)==0);
  utc.year=1900;CHECK(!SystemTimeToFileTime(&utc,&stamp)&&GetLastError()==87);
  WORD fatDate,fatTime;
  HDC savedDC=GetDC(NULL);POINT savedPosition;
  POINT shapePoints[3]={{1,1},{9,1},{5,9}};
  POINT groupedPoints[4]={{1,1},{4,1},{7,7},{9,7}};DWORD groupedCounts[2]={2,2};
  CHECK(PolyPolyline(savedDC,groupedPoints,groupedCounts,2));groupedCounts[1]=1;CHECK(!PolyPolyline(savedDC,groupedPoints,groupedCounts,2)&&GetLastError()==87);
  CHECK(MoveToEx(savedDC,7,8,NULL)&&PolylineTo(savedDC,shapePoints,3));
  CHECK(GetCurrentPositionEx(savedDC,&savedPosition)&&savedPosition.x==5&&savedPosition.y==9&&PolylineTo(savedDC,NULL,0));
  CHECK(GetPolyFillMode(savedDC)==1&&SetPolyFillMode(savedDC,2)==1&&GetPolyFillMode(savedDC)==2);
  CHECK(Polygon(savedDC,shapePoints,3)&&Polyline(savedDC,shapePoints,3));
  CHECK(!Polygon(savedDC,shapePoints,1)&&GetLastError()==87);
  DWORD ansiFontData[23]={0},ansiFontCopy[15]={0};
  WORD* ansiFace=(WORD*)((BYTE*)ansiFontData+28);ansiFace[0]=0xff21;ansiFace[1]=0x100;ansiFace[2]=0x2212;ansiFace[3]=0xd83d;ansiFace[4]=0xde00;
  HANDLE ansiMappedFont=CreateFontIndirectW(ansiFontData);CHECK(ansiMappedFont&&GetObjectA(ansiMappedFont,60,ansiFontCopy)==60);
  BYTE* ansiMappedFace=(BYTE*)ansiFontCopy+28;CHECK(ansiMappedFace[0]==65&&ansiMappedFace[1]==65&&ansiMappedFace[2]==45&&ansiMappedFace[3]==63&&ansiMappedFace[4]==63&&ansiMappedFace[5]==0&&DeleteObject(ansiMappedFont));
  DWORD logicalFont[23]={0},fontCopy[23]={0};logicalFont[0]=(DWORD)-17;logicalFont[4]=700;logicalFont[7]=65;
  HANDLE fontA=CreateFontIndirectA(logicalFont),fontW=CreateFontIndirectW(logicalFont);
  CHECK(fontA&&fontW&&GetObjectW(fontA,92,fontCopy)==92&&fontCopy[0]==(DWORD)-17&&fontCopy[4]==700&&fontCopy[7]==65);
  CHECK(GetObjectA(fontW,60,fontCopy)==60&&((BYTE*)fontCopy)[28]==65&&DeleteObject(fontA)&&DeleteObject(fontW));
  RECT paintRect={1,1,4,4};HANDLE paintBrush=CreateSolidBrush(0x123456);
  CHECK(FillRect(savedDC,&paintRect,paintBrush)&&FrameRect(savedDC,&paintRect,paintBrush));
  paintRect.left=5;CHECK(!FrameRect(savedDC,&paintRect,paintBrush)&&FillRect(savedDC,&paintRect,paintBrush));
  CHECK(DeleteObject(paintBrush));
  CHECK(GetDCPenColor(savedDC)==0&&GetDCBrushColor(savedDC)==0xffffff);
  CHECK(SetDCPenColor(savedDC,0x123456)==0&&SetDCBrushColor(savedDC,0xabcdef)==0xffffff);
  CHECK(SaveDC(savedDC)==1&&SetDCPenColor(savedDC,7)==0x123456&&SetDCBrushColor(savedDC,8)==0xabcdef);
  CHECK(RestoreDC(savedDC,-1)&&GetDCPenColor(savedDC)==0x123456&&GetDCBrushColor(savedDC)==0xabcdef);
  DWORD penDescription[4],brushDescription[3];
  DWORD indirectPenData[4]={0,(DWORD)-3,99,0x123456},indirectBrushData[3]={1,0xabcdef,99};
  HANDLE indirectPen=CreatePenIndirect(indirectPenData),indirectBrush=CreateBrushIndirect(indirectBrushData);
  CHECK(indirectPen&&indirectBrush&&GetObjectW(indirectPen,16,penDescription)==16&&penDescription[1]==3&&penDescription[2]==0&&penDescription[3]==0x123456);
  CHECK(GetObjectA(indirectBrush,12,brushDescription)==12&&brushDescription[0]==1&&brushDescription[1]==0&&brushDescription[2]==0);
  CHECK(DeleteObject(indirectPen)&&DeleteObject(indirectBrush));
  CHECK(GetObjectA(GetCurrentObject(savedDC,1),0,NULL)==16);
  CHECK(GetObjectW(GetCurrentObject(savedDC,1),16,penDescription)==16&&penDescription[0]==0&&penDescription[1]==1&&penDescription[2]==0&&penDescription[3]==0);
  CHECK(GetObjectA(GetCurrentObject(savedDC,2),12,brushDescription)==12&&brushDescription[0]==0&&brushDescription[1]==0xffffff&&brushDescription[2]==0);
  CHECK(!GetObjectW(GetCurrentObject(savedDC,1),15,penDescription));
  CHECK(GetTextColor(savedDC)==0&&GetBkColor(savedDC)==0xffffff&&GetBkMode(savedDC)==2&&GetTextAlign(savedDC)==0);
  CHECK(GetObjectType(savedDC)==3&&GetObjectType(GetCurrentObject(savedDC,1))==1&&GetObjectType(GetCurrentObject(savedDC,2))==2&&GetObjectType(GetCurrentObject(savedDC,6))==6);
  CHECK(GetTextColor(NULL)==0xffffffff&&GetBkMode(NULL)==0&&!GetCurrentObject(savedDC,99)&&GetLastError()==87);
  CHECK(savedDC&&MoveToEx(savedDC,3,4,NULL)&&SaveDC(savedDC)==1);
  CHECK(MoveToEx(savedDC,10,20,NULL)&&SaveDC(savedDC)==2&&MoveToEx(savedDC,30,40,NULL));
  CHECK(RestoreDC(savedDC,-1)&&GetCurrentPositionEx(savedDC,&savedPosition)&&savedPosition.x==10&&savedPosition.y==20);
  CHECK(RestoreDC(savedDC,1)&&GetCurrentPositionEx(savedDC,&savedPosition)&&savedPosition.x==3&&savedPosition.y==4);
  CHECK(!RestoreDC(savedDC,-1)&&GetLastError()==87);CHECK(ReleaseDC(NULL,savedDC));
  RECT rectA,rectB,rectOut;POINT rectPoint={0,0};
  CHECK(SetRect(&rectA,0,0,10,10)&&SetRect(&rectB,0,0,5,10));
  CHECK(PtInRect(&rectA,rectPoint));rectPoint.x=10;CHECK(!PtInRect(&rectA,rectPoint));
  CHECK(SubtractRect(&rectOut,&rectA,&rectB)&&rectOut.left==5);
  CHECK(IntersectRect(&rectOut,&rectA,&rectB)&&EqualRect(&rectOut,&rectB));
  CHECK(UnionRect(&rectOut,&rectA,&rectB)&&EqualRect(&rectOut,&rectA));
  CHECK(CopyRect(&rectOut,&rectB)&&OffsetRect(&rectOut,1,2)&&InflateRect(&rectOut,1,2)&&rectOut.left==0&&rectOut.right==7);
  CHECK(SetRectEmpty(&rectOut)&&IsRectEmpty(&rectOut));
  CHECK(MulDiv(5,3,2)==8&&MulDiv(-5,3,2)==-8&&MulDiv(5,3,-2)==-8);
  CHECK(MulDiv(2147483647,2147483647,2147483647)==2147483647);
  CHECK(MulDiv(1,1,0)==-1&&MulDiv(2147483647,2,1)==-1&&MulDiv((int)0x80000000,1,2)==-1);
  WORD shellLine[]={'p',' ','"','a',' ','b','"',' ','c',0};int shellCount=0;
  WORD** shellArgs=CommandLineToArgvW(shellLine,&shellCount);
  CHECK(shellArgs&&shellCount==3&&shellArgs[1][0]=='a'&&shellArgs[1][1]==' '&&shellArgs[1][2]=='b'&&shellArgs[2][0]=='c');
  CHECK(LocalFree(shellArgs)==NULL);
  WORD typedText[]={'A','0',' ',0},charTypes[4];
  CHECK(GetStringTypeW(1,typedText,-1,charTypes)&&(charTypes[0]&0x101)==0x101&&(charTypes[1]&4)&&(charTypes[2]&8)&&(charTypes[3]&0x20));
  CHECK(GetStringTypeW(2,typedText,3,charTypes)&&charTypes[0]==1&&charTypes[1]==3&&charTypes[2]==10);
  CHECK(GetStringTypeW(4,typedText,3,charTypes)&&(charTypes[0]&0x8000));
  CHECK(!GetStringTypeW(3,typedText,3,charTypes)&&GetLastError()==1004);
  CPINFO cpInfo;CPINFOEXA cpInfoA;CPINFOEXW cpInfoW;
  CHECK(sizeof(CPINFO)==20&&sizeof(CPINFOEXA)==284&&sizeof(CPINFOEXW)==544);
  CHECK(IsValidCodePage(65001)&&!IsValidCodePage(0));
  CHECK(GetCPInfo(65001,&cpInfo)&&cpInfo.maxCharSize==4&&cpInfo.defaultChar[0]=='?');
  CHECK(GetCPInfoExA(0,0,&cpInfoA)&&cpInfoA.codePage==1252&&cpInfoA.name[0]=='1');
  CHECK(GetCPInfoExW(65001,0,&cpInfoW)&&cpInfoW.unicodeDefault==0xfffd&&cpInfoW.name[0]=='6');
  CHECK(!GetCPInfoExA(1252,1,&cpInfoA)&&GetLastError()==1004);
  const char utf8Bom[]={ (char)0xef,(char)0xbb,(char)0xbf,'A',0 };WORD decoded[8];char encoded[16];
  CHECK(MultiByteToWideChar(65001,8,utf8Bom,-1,decoded,8)==3&&decoded[0]==0xfeff&&decoded[1]=='A');
  CHECK(WideCharToMultiByte(65001,0x80,decoded,3,encoded,16,NULL,NULL)==5&&encoded[0]==(char)0xef);
  decoded[0]=0xd800;CHECK(!WideCharToMultiByte(65001,0x80,decoded,1,encoded,16,NULL,NULL)&&GetLastError()==1113);
  BOOL usedFallback=0;WORD legacyText[]={0x221e,0};
  CHECK(WideCharToMultiByte(1252,0,legacyText,1,encoded,16,NULL,&usedFallback)==1&&encoded[0]=='8'&&!usedFallback);
  CHECK(WideCharToMultiByte(1252,0x400,legacyText,1,encoded,16,"!",&usedFallback)==1&&encoded[0]=='!'&&usedFallback);
  CHECK(WideCharToMultiByte(437,0,legacyText,1,encoded,16,NULL,NULL)==1&&(BYTE)encoded[0]==0xec);
  CHECK(MultiByteToWideChar(1,0,encoded,1,decoded,8)==1&&decoded[0]==0x221e);
  WORD ordinalA[]={'A',0,'x',0},ordinalB[]={'a',0,'y',0};
  CHECK(CompareStringOrdinal(ordinalA,-1,ordinalB,-1,1)==2);
  CHECK(CompareStringOrdinal(ordinalA,3,ordinalB,3,1)==1);
  CHECK(CompareStringOrdinal(ordinalA,1,ordinalB,1,0)==1);
  CHECK(!CompareStringOrdinal(ordinalA,1,ordinalB,1,2)&&GetLastError()==87);
  WORD searchSource[]={'a','b','A','B',0},searchValue[]={'a','b',0};
  CHECK(FindStringOrdinal(0,searchSource,-1,searchValue,-1,1)==0);
  CHECK(FindStringOrdinal(0x800000,searchSource,-1,searchValue,-1,1)==2);
  CHECK(FindStringOrdinal(0x100000,searchSource,-1,searchValue,-1,1)==0);
  CHECK(FindStringOrdinal(0x200000,searchSource,-1,searchValue,-1,0)==-1&&GetLastError()==0);
  CHECK(FindStringOrdinal(1,searchSource,-1,searchValue,-1,0)==-1&&GetLastError()==1004);
  CHECK(DosDateTimeToFileTime(0x21,0,&stamp));CHECK(FileTimeToDosDateTime(&stamp,&fatDate,&fatTime));
  CHECK(fatDate==0x21&&fatTime==0);stamp.low++;
  CHECK(FileTimeToDosDateTime(&stamp,&fatDate,&fatTime)&&fatTime==1);
  CHECK(!DosDateTimeToFileTime(0,0,&stamp)&&GetLastError()==87);
  InitializeConditionVariable(&condition);WakeConditionVariable(&condition);WakeAllConditionVariable(&condition);
  AcquireSRWLockExclusive(&srw);CHECK(!SleepConditionVariableSRW(&condition,&srw,0,0)&&GetLastError()==1460);ReleaseSRWLockExclusive(&srw);
  AcquireSRWLockShared(&srw);CHECK(!SleepConditionVariableSRW(&condition,&srw,0,1)&&GetLastError()==1460);ReleaseSRWLockShared(&srw);
  InitializeCriticalSection(&critical);EnterCriticalSection(&critical);
  CHECK(!SleepConditionVariableCS(&condition,&critical,0)&&GetLastError()==1460);
  CHECK(critical.recursion==1&&critical.owner!=NULL);LeaveCriticalSection(&critical);DeleteCriticalSection(&critical);
  CHECK(GetEnvironmentVariableA("b86_test",finalPath,256)==5&&finalPath[0]=='v');
  CHECK(ExpandEnvironmentStringsA("[%B86_TEST%]",finalPath,256)==8&&finalPath[0]=='['&&finalPath[6]==']');
  CHECK(SetEnvironmentVariableA("B86_TEST",""));
  CHECK(GetEnvironmentVariableA("B86_TEST",NULL,0)==1);
  CHECK(GetEnvironmentVariableA("B86_TEST",finalPath,256)==0&&finalPath[0]==0);
  CHECK(FreeEnvironmentStringsA(GetEnvironmentStrings()));
  CHECK(FreeEnvironmentStringsW(GetEnvironmentStringsW()));
  CHECK(SetEnvironmentVariableA("B86_TEST",NULL));
  CHECK(GetEnvironmentVariableA("B86_TEST",finalPath,256)==0&&GetLastError()==203);
  CHECK(DuplicateHandle(self,self,self,&process,0,0,2));
  CHECK(DuplicateHandle(self,GetCurrentThread(),self,&thread,0,0,2));
  CHECK(GetProcessId(process)==4&&GetThreadId(thread)==8);
  CHECK(GetExitCodeProcess(process,&code)&&code==259);
  CHECK(GetExitCodeThread(thread,&code)&&code==259);
  CHECK(WaitForSingleObject(thread,0)==258);
  CHECK(CloseHandle(process)&&CloseHandle(thread));
  puts("Handle checks passed.");
  ExitProcess(0);
}
