#include "minwin.h"
#define CHECK(expression) do { if(!(expression)) { printf("Handle failure at line %d\n",__LINE__); ExitProcess(__LINE__); } } while(0)
void mainCRTStartup(void){
  HANDLE self=GetCurrentProcess(),file,copy,process,thread;
  DWORD flags,count,code;
  char bytes[4];
  long long position;
  long long endOfFile;
  FILETIME creation={123,30000000},access={456,30000001},write={789,30000002},returned;
  BY_HANDLE_FILE_INFORMATION info;
  FILE_STANDARD_INFO standard;
  FILE_ID_INFO identity;
  FILE_ATTRIBUTE_TAG_INFO tag;
  FILE_NAME_BUFFER filename;
  DWORD originalId;
  const WORD wideFile[]={'h','a','n','d','l','e','s','.','t','x','t',0};
  file=CreateFileA("handles.txt",GENERIC_READ|GENERIC_WRITE,0,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(GetFileInformationByHandle(file,&info));originalId=info.idLow;
  CHECK(DuplicateHandle(self,file,self,&copy,0,1,2));
  CHECK(copy!=file);
  CHECK(GetHandleInformation(copy,&flags)&&flags==1);
  CHECK(SetHandleInformation(file,2,2));
  CHECK(!CloseHandle(file)&&GetLastError()==6);
  CHECK(WriteFile(file,"ab",2,&count,NULL)&&count==2);
  CHECK(WriteFile(copy,"cd",2,&count,NULL)&&count==2);
  CHECK(SetFilePointer(copy,0,NULL,0)==0);
  CHECK(ReadFile(file,bytes,2,&count,NULL)&&count==2&&bytes[0]=='a'&&bytes[1]=='b');
  CHECK(SetHandleInformation(file,2,0)&&CloseHandle(file));
  CHECK(ReadFile(copy,bytes,2,&count,NULL)&&count==2&&bytes[0]=='c'&&bytes[1]=='d');
  CHECK(SetFilePointerEx(copy,0x20000000000003LL,&position,0)&&position==0x20000000000003LL);
  CHECK(WriteFile(copy,NULL,0,&count,NULL)&&count==0);
  CHECK(ReadFile(copy,bytes,1,&count,NULL)&&count==0);
  CHECK(GetFileSizeEx(copy,&position)&&position==4);
  CHECK(!WriteFile(copy,"x",1,&count,NULL)&&GetLastError()==112);
  CHECK(SetFilePointerEx(copy,-1,&position,1)&&position==0x20000000000002LL);
  CHECK(SetFilePointerEx(copy,-2,&position,2)&&position==2);
  CHECK(SetEndOfFile(copy));
  CHECK(GetFileSizeEx(copy,&position)&&position==2);
  endOfFile=8;
  CHECK(SetFileInformationByHandle(copy,6,&endOfFile,sizeof(endOfFile)));
  CHECK(GetFileSizeEx(copy,&position)&&position==8);
  CHECK(SetFilePointerEx(copy,0,&position,1)&&position==2);
  endOfFile=-1;
  CHECK(!SetFileInformationByHandle(copy,6,&endOfFile,sizeof(endOfFile))&&GetLastError()==87);
  endOfFile=2;
  CHECK(SetFileInformationByHandle(copy,6,&endOfFile,sizeof(endOfFile)));
  CHECK(SetFileTime(copy,&creation,&access,&write));
  CHECK(GetFileTime(copy,NULL,NULL,&returned)&&returned.low==789&&returned.high==30000002);
  CHECK(GetFileInformationByHandle(copy,&info)&&info.idLow==originalId&&info.sizeLow==2&&info.links==1);
  CHECK(info.creation.low==123&&info.access.low==456&&info.write.low==789);
  CHECK(SetFileAttributesA("handles.txt",3)&&GetFileAttributesA("handles.txt")==3);
  CHECK(SetFileAttributesW(wideFile,128)&&GetFileAttributesA("handles.txt")==128);
  CHECK(sizeof(standard)==24&&sizeof(identity)==24&&sizeof(tag)==8);
  CHECK(GetFileInformationByHandleEx(copy,1,&standard,sizeof(standard)));
  CHECK(standard.endOfFile==2&&standard.allocationSize==2&&standard.links==1&&!standard.deletePending&&!standard.directory);
  CHECK(GetFileInformationByHandleEx(copy,18,&identity,sizeof(identity)));
  CHECK(identity.volume==0xB8600001ULL&&*(DWORD*)identity.id==originalId);
  CHECK(GetFileInformationByHandleEx(copy,9,&tag,sizeof(tag))&&tag.attributes==128&&tag.reparseTag==0);
  CHECK(GetFileInformationByHandleEx(copy,2,&filename,sizeof(filename))&&filename.name[0]=='\\');
  CHECK(!GetFileInformationByHandleEx(copy,2,&filename,8)&&GetLastError()==234&&filename.length>4);
  CHECK(CloseHandle(copy));
  /* A deleted name stays reserved until the last open file object closes. */
  file=CreateFileA("pending.txt",GENERIC_READ|GENERIC_WRITE,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(WriteFile(file,"xy",2,&count,NULL)&&count==2);
  CHECK(DuplicateHandle(self,file,self,&copy,0,0,2));
  CHECK(DeleteFileA("pending.txt"));
  CHECK(GetFileInformationByHandleEx(copy,1,&standard,sizeof(standard))&&standard.deletePending&&standard.links==0);
  CHECK(CreateFileA("pending.txt",GENERIC_READ,7,NULL,2,0,NULL)==INVALID_HANDLE&&GetLastError()==5);
  CHECK(CloseHandle(file));
  CHECK(SetFilePointer(copy,0,NULL,0)==0);
  CHECK(ReadFile(copy,bytes,2,&count,NULL)&&count==2&&bytes[0]=='x'&&bytes[1]=='y');
  CHECK(CloseHandle(copy));
  CHECK(CreateFileA("pending.txt",GENERIC_READ,7,NULL,3,0,NULL)==INVALID_HANDLE&&GetLastError()==2);
  file=CreateFileA("temporary.txt",GENERIC_READ|GENERIC_WRITE,7,NULL,2,0x04000000,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(DuplicateHandle(self,file,self,&copy,0,0,3));
  CHECK(WriteFile(copy,"z",1,&count,NULL)&&count==1);
  CHECK(CloseHandle(copy));
  CHECK(CreateFileA("temporary.txt",GENERIC_READ,7,NULL,3,0,NULL)==INVALID_HANDLE&&GetLastError()==2);
  CHECK(DuplicateHandle(self,self,self,&process,0,0,2));
  CHECK(DuplicateHandle(self,GetCurrentThread(),self,&thread,0,0,2));
  CHECK(GetProcessId(process)==4&&GetThreadId(thread)==8);
  CHECK(GetExitCodeProcess(process,&code)&&code==259);
  CHECK(GetExitCodeThread(thread,&code)&&code==259);
  CHECK(WaitForSingleObject(thread,0)==258);
  CHECK(CloseHandle(process)&&CloseHandle(thread));
  puts("Handle checks passed.");
  ExitProcess(0);
}
