#include "minwin.h"
int _fltused=0;
unsigned long __readfsdword(unsigned long);
#pragma intrinsic(__readfsdword)
#define CHECK(expression) do { if(!(expression)) { printf("Handle failure at line %d\n",__LINE__); ExitProcess(__LINE__); } } while(0)
static HWND lifetimeWindows[4];
static DWORD creationWide,creationCount,textMessageCount;
static long WINAPI encodingProc(HWND h,DWORD msg,DWORD wp,long lp){
  if(msg==12){
    textMessageCount++;
    if(creationWide){WORD *text=(WORD*)lp;CHECK(text[0]=='C'&&text[3]==233&&text[4]==0);}
    else {char *text=(char*)lp;CHECK(text[0]=='C'&&(unsigned char)text[3]==233&&text[4]==' '&&text[5]=='A'&&text[6]==0);}
    return 7;
  }
  if(msg==129||msg==1){
    DWORD *cs=(DWORD*)lp;creationCount++;
    if(creationWide){WORD *title=(WORD*)cs[9],*name=(WORD*)cs[10];CHECK(title[0]=='C'&&title[3]==233&&title[4]==0);CHECK(name[0]=='W'&&name[1]==233&&name[2]==0);}
    else {char *title=(char*)cs[9],*name=(char*)cs[10];CHECK(title[0]=='C'&&(unsigned char)title[3]==233&&title[4]==' '&&title[5]=='A'&&title[6]==0);CHECK(name[0]=='A'&&(unsigned char)name[1]==233&&name[2]==0);}
  }
  return msg==129?1:0;
}
static DWORD focusCount,focusMessages[8];
static HWND focusObserved[8],focusOther[8];
static DWORD lifetimeLog[8],lifetimeCount,enableLog[5],enableState[5],enableCount;
static long WINAPI lifetimeProc(HWND h,DWORD msg,DWORD wp,long lp){
  if((msg==7||msg==8)&&focusCount<8){focusMessages[focusCount]=msg;focusOther[focusCount]=(HWND)wp;focusObserved[focusCount++]=GetFocus();}
  if((msg==31||msg==10)&&enableCount<5){enableLog[enableCount]=msg;enableState[enableCount++]=IsWindowEnabled(h);}
  if(msg==2||msg==130){for(int i=0;i<4;i++)if(h==lifetimeWindows[i]&&lifetimeCount<8)lifetimeLog[lifetimeCount++]=i*256+msg;}
  return DefWindowProcA(h,msg,wp,lp);
}
static DWORD rejectStage,rejectLog[4],rejectCount;
static HWND rejectedWindow;
static long WINAPI rejectProc(HWND h,DWORD msg,DWORD wp,long lp){
  if(msg==129||msg==1||msg==2||msg==130){if(rejectCount<4)rejectLog[rejectCount++]=msg;rejectedWindow=h;}
  if(msg==129)return rejectStage==129?0:1;
  if(msg==1)return -1;
  return DefWindowProcA(h,msg,wp,lp);
}
static DWORD propertyEnumCount,propertyEnumSum;
static BOOL WINAPI enumPropertyA(HWND h,char *name,HANDLE data){propertyEnumCount++;propertyEnumSum+=(DWORD)data;CHECK(GetPropA(h,name)==data);return 7;}
static BOOL WINAPI enumPropertyW(HWND h,WORD *name,HANDLE data){propertyEnumCount++;propertyEnumSum+=(DWORD)data;CHECK(GetPropW(h,name)==data);return 7;}
static BOOL WINAPI enumPropertyExA(HWND h,char *name,HANDLE data,DWORD param){CHECK(param==0xabcdef12);CHECK(GetPropA(h,name)==data);return 0;}
static BOOL WINAPI enumPropertyExW(HWND h,WORD *name,HANDLE data,DWORD param){CHECK(param==99);propertyEnumCount++;CHECK(RemovePropW(h,name)==data);return 7;}
static DWORD initializationCalls;
static BOOL WINAPI initializeOnce(DWORD *once,void *parameter,void **context){
  initializationCalls++;if(initializationCalls==1){SetLastError(123);return 0;}
  *context=parameter;return 1;
}
void mainCRTStartup(void){
  WNDCLASSA encodingA={0};encodingA.proc=encodingProc;encodingA.name="A\xe9";CHECK(RegisterClassA(&encodingA));
  WORD aName[]={'A',233,0},wTitle[]={'C','a','f',233,' ',256,0};
  HWND encodingWindow=CreateWindowExW(0,aName,wTitle,0x80000000,0,0,20,20,NULL,NULL,NULL,NULL);CHECK(encodingWindow&&creationCount==2);
  CHECK(SendMessageW(encodingWindow,12,99,(long)wTitle)==7);CHECK(SetWindowTextW(encodingWindow,wTitle)==1);CHECK(textMessageCount==2);CHECK(DestroyWindow(encodingWindow));
  WORD wName[]={'W',233,0};WNDCLASSW encodingW={0};encodingW.proc=encodingProc;encodingW.name=wName;CHECK(RegisterClassW(&encodingW));creationWide=1;creationCount=0;
  encodingWindow=CreateWindowExA(0,"W\xe9","Caf\xe9",0x80000000,0,0,20,20,NULL,NULL,NULL,NULL);CHECK(encodingWindow&&creationCount==2);
  CHECK(SendMessageA(encodingWindow,12,99,(long)"Caf\xe9")==7);CHECK(SetWindowTextA(encodingWindow,"Caf\xe9")==1);CHECK(textMessageCount==4);CHECK(DestroyWindow(encodingWindow));
  HANDLE self=GetCurrentProcess(),file,copy,process,thread;
  DWORD flags,count,code;
  char bytes[4];
  char finalPath[256];
  WORD finalWide[256];
  long long position;
  long long endOfFile;
  FILETIME creation={123,30000000},access={456,30000001},write={789,30000002},returned;
  BY_HANDLE_FILE_INFORMATION info;
  FILE_STANDARD_INFO standard;
  FILE_ID_INFO identity;
  FILE_ATTRIBUTE_TAG_INFO tag;
  FILE_NAME_BUFFER filename;
  FILE_RENAME_BUFFER rename;
  DWORD originalId;
  DWORD tls[65],index;
  DWORD once=0,manual=0;BOOL pending;void *onceContext=NULL;
  CRITICAL_SECTION critical;
  BYTE disposition;
  const WORD wideFile[]={'h','a','n','d','l','e','s','.','t','x','t',0};
  file=CreateFileA("handles.txt",GENERIC_READ|GENERIC_WRITE,0,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(GetFileInformationByHandle(file,&info));originalId=info.idLow;
  CHECK(DuplicateHandle(self,file,self,&copy,0,1,2));
  CHECK(copy!=file);
  CHECK(GetHandleInformation(copy,&flags)&&flags==1);
  CHECK(SetHandleInformation(file,2,2));
  CHECK(!CloseHandle(file)&&GetLastError()==6);
  CHECK(WriteFile(file,"ab",2,&count,NULL)&&count==2);
  CHECK(WriteFile(copy,"cd",2,&count,NULL)&&count==2);
  CHECK(SetFilePointer(copy,0,NULL,0)==0);
  CHECK(ReadFile(file,bytes,2,&count,NULL)&&count==2&&bytes[0]=='a'&&bytes[1]=='b');
  CHECK(SetHandleInformation(file,2,0)&&CloseHandle(file));
  CHECK(ReadFile(copy,bytes,2,&count,NULL)&&count==2&&bytes[0]=='c'&&bytes[1]=='d');
  CHECK(SetFilePointerEx(copy,0x20000000000003LL,&position,0)&&position==0x20000000000003LL);
  CHECK(WriteFile(copy,NULL,0,&count,NULL)&&count==0);
  CHECK(ReadFile(copy,bytes,1,&count,NULL)&&count==0);
  CHECK(GetFileSizeEx(copy,&position)&&position==4);
  CHECK(!WriteFile(copy,"x",1,&count,NULL)&&GetLastError()==112);
  CHECK(SetFilePointerEx(copy,-1,&position,1)&&position==0x20000000000002LL);
  CHECK(SetFilePointerEx(copy,-2,&position,2)&&position==2);
  CHECK(SetEndOfFile(copy));
  CHECK(GetFileSizeEx(copy,&position)&&position==2);
  endOfFile=8;
  CHECK(SetFileInformationByHandle(copy,6,&endOfFile,sizeof(endOfFile)));
  CHECK(GetFileSizeEx(copy,&position)&&position==8);
  CHECK(SetFilePointerEx(copy,0,&position,1)&&position==2);
  endOfFile=-1;
  CHECK(!SetFileInformationByHandle(copy,6,&endOfFile,sizeof(endOfFile))&&GetLastError()==87);
  endOfFile=2;
  CHECK(SetFileInformationByHandle(copy,6,&endOfFile,sizeof(endOfFile)));
  CHECK(SetFileTime(copy,&creation,&access,&write));
  CHECK(GetFileTime(copy,NULL,NULL,&returned)&&returned.low==789&&returned.high==30000002);
  CHECK(GetFileInformationByHandle(copy,&info)&&info.idLow==originalId&&info.sizeLow==2&&info.links==1);
  CHECK(info.creation.low==123&&info.access.low==456&&info.write.low==789);
  CHECK(SetFileAttributesA("handles.txt",3)&&GetFileAttributesA("handles.txt")==3);
  CHECK(SetFileAttributesW(wideFile,128)&&GetFileAttributesA("handles.txt")==128);
  CHECK(sizeof(standard)==24&&sizeof(identity)==24&&sizeof(tag)==8);
  CHECK(GetFileInformationByHandleEx(copy,1,&standard,sizeof(standard)));
  CHECK(standard.endOfFile==2&&standard.allocationSize==2&&standard.links==1&&!standard.deletePending&&!standard.directory);
  CHECK(GetFileInformationByHandleEx(copy,18,&identity,sizeof(identity)));
  CHECK(identity.volume==0xB8600001ULL&&*(DWORD*)identity.id==originalId);
  CHECK(GetFileInformationByHandleEx(copy,9,&tag,sizeof(tag))&&tag.attributes==128&&tag.reparseTag==0);
  CHECK(GetFileInformationByHandleEx(copy,2,&filename,sizeof(filename))&&filename.name[0]=='\\');
  CHECK(!GetFileInformationByHandleEx(copy,2,&filename,8)&&GetLastError()==234&&filename.length>4);
  CHECK(CloseHandle(copy));
  file=CreateFileA("handles.txt",GENERIC_READ,7,NULL,3,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  count=GetFinalPathNameByHandleW(file,NULL,0,0);
  CHECK(count>5&&count<256&&GetFinalPathNameByHandleW(file,finalWide,256,0)==count-1);
  CHECK(finalWide[0]=='\\'&&finalWide[1]=='\\'&&finalWide[2]=='?'&&finalWide[3]=='\\');
  CHECK(GetFinalPathNameByHandleA(file,finalPath,256,8)>0);
  copy=CreateFileA(finalPath,GENERIC_READ,7,NULL,3,0,NULL);
  CHECK(copy!=INVALID_HANDLE&&CloseHandle(copy)&&CloseHandle(file));
  /* A deleted name stays reserved until the last open file object closes. */
  file=CreateFileA("pending.txt",GENERIC_READ|GENERIC_WRITE,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(WriteFile(file,"xy",2,&count,NULL)&&count==2);
  CHECK(DuplicateHandle(self,file,self,&copy,0,0,2));
  CHECK(DeleteFileA("pending.txt"));
  CHECK(GetFileInformationByHandleEx(copy,1,&standard,sizeof(standard))&&standard.deletePending&&standard.links==0);
  CHECK(CreateFileA("pending.txt",GENERIC_READ,7,NULL,2,0,NULL)==INVALID_HANDLE&&GetLastError()==5);
  CHECK(CloseHandle(file));
  CHECK(SetFilePointer(copy,0,NULL,0)==0);
  CHECK(ReadFile(copy,bytes,2,&count,NULL)&&count==2&&bytes[0]=='x'&&bytes[1]=='y');
  CHECK(CloseHandle(copy));
  CHECK(CreateFileA("pending.txt",GENERIC_READ,7,NULL,3,0,NULL)==INVALID_HANDLE&&GetLastError()==2);
  file=CreateFileA("temporary.txt",GENERIC_READ|GENERIC_WRITE,7,NULL,2,0x04000000,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(DuplicateHandle(self,file,self,&copy,0,0,3));
  CHECK(WriteFile(copy,"z",1,&count,NULL)&&count==1);
  CHECK(CloseHandle(copy));
  CHECK(CreateFileA("temporary.txt",GENERIC_READ,7,NULL,3,0,NULL)==INVALID_HANDLE&&GetLastError()==2);
  file=CreateFileA("disposition.txt",GENERIC_READ|GENERIC_WRITE|0x10000,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(DuplicateHandle(self,file,self,&copy,0,0,2));
  disposition=1;CHECK(SetFileInformationByHandle(file,4,&disposition,1));
  CHECK(GetFileInformationByHandleEx(copy,1,&standard,sizeof(standard))&&standard.deletePending&&standard.links==0);
  disposition=0;CHECK(SetFileInformationByHandle(copy,4,&disposition,1));
  CHECK(GetFileInformationByHandleEx(file,1,&standard,sizeof(standard))&&!standard.deletePending&&standard.links==1);
  disposition=1;CHECK(SetFileInformationByHandle(copy,4,&disposition,1));
  CHECK(CloseHandle(file)&&CloseHandle(copy));
  CHECK(CreateFileA("disposition.txt",GENERIC_READ,7,NULL,3,0,NULL)==INVALID_HANDLE&&GetLastError()==2);
  file=CreateFileA("rename-source.txt",GENERIC_READ|GENERIC_WRITE|0x10000,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE);
  CHECK(GetFileInformationByHandle(file,&info));originalId=info.idLow;
  memset(&rename,0,sizeof(rename));rename.length=10;
  rename.name[0]='r';rename.name[1]='.';rename.name[2]='t';rename.name[3]='x';rename.name[4]='t';
  CHECK((char*)rename.name-(char*)&rename==12);
  CHECK(SetFileInformationByHandle(file,3,&rename,sizeof(rename)));
  CHECK(GetFileInformationByHandle(file,&info)&&info.idLow==originalId);
  CHECK(CreateFileA("rename-source.txt",GENERIC_READ,7,NULL,3,0,NULL)==INVALID_HANDLE&&GetLastError()==2);
  CHECK(WriteFile(file,"r",1,&count,NULL)&&count==1);
  CHECK(CloseHandle(file)&&DeleteFileA("r.txt"));
  CHECK(CreateDirectoryA("rename-dir",NULL));
  file=CreateFileA("rename-dir/child",GENERIC_WRITE,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE&&WriteFile(file,"d",1,&count,NULL)&&CloseHandle(file));
  file=CreateFileA("rename-dir",0x10000,7,NULL,3,0x02000000,NULL);
  CHECK(file!=INVALID_HANDLE&&SetFileInformationByHandle(file,3,&rename,sizeof(rename)));
  CHECK(CloseHandle(file)&&MoveFileA("r.txt","rename-dir"));
  file=CreateFileA("rename-dir/child",GENERIC_READ,7,NULL,3,0,NULL);
  CHECK(file!=INVALID_HANDLE&&ReadFile(file,bytes,1,&count,NULL)&&count==1&&bytes[0]=='d');
  CHECK(CloseHandle(file)&&DeleteFileA("rename-dir/child")&&RemoveDirectoryA("rename-dir"));
  file=CreateFileA("append.txt",4,7,NULL,2,0,NULL);
  CHECK(file!=INVALID_HANDLE&&WriteFile(file,"ab",2,&count,NULL)&&count==2);
  CHECK(SetFilePointer(file,0,NULL,0)==0);
  CHECK(WriteFile(file,"c",1,&count,NULL)&&count==1);
  CHECK(SetFilePointerEx(file,0,&position,1)&&position==3);
  CHECK(!SetEndOfFile(file)&&GetLastError()==5);
  CHECK(CloseHandle(file));
  file=CreateFileA("append.txt",GENERIC_READ,7,NULL,3,0,NULL);
  CHECK(file!=INVALID_HANDLE&&ReadFile(file,bytes,3,&count,NULL)&&count==3);
  CHECK(bytes[0]=='a'&&bytes[1]=='b'&&bytes[2]=='c');
  CHECK(CloseHandle(file)&&DeleteFileA("append.txt"));
  CHECK(GetTempFileNameA("C:\\Temp","b86",0,finalPath)!=0);
  file=CreateFileA(finalPath,GENERIC_READ,7,NULL,3,0,NULL);
  CHECK(file!=INVALID_HANDLE&&GetFileSizeEx(file,&position)&&position==0);
  CHECK(CloseHandle(file)&&DeleteFileA(finalPath));
  finalWide[0]='.';finalWide[1]=0;rename.name[0]='t';rename.name[1]='m';rename.name[2]='p';rename.name[3]=0;
  CHECK(GetTempFileNameW(finalWide,rename.name,0x12345,filename.name)==0x2345);
  for(index=0;index<65;index++){tls[index]=TlsAlloc();CHECK(tls[index]!=0xFFFFFFFF);CHECK(TlsGetValue(tls[index])==NULL);}
  CHECK(TlsSetValue(tls[64],(void*)0xFEDCBA98));
  CHECK(*(DWORD*)(__readfsdword(0xF94)+(tls[64]-64)*4)==0xFEDCBA98);
  CHECK(TlsSetValue(tls[0],(void*)0x12345678));
  CHECK(*(DWORD*)(__readfsdword(0x18)+0xE10+tls[0]*4)==0x12345678);
  SetLastError(123);CHECK(TlsGetValue2(tls[64])==(void*)0xFEDCBA98&&GetLastError()==123);
  CHECK(TlsGetValue(tls[64])==(void*)0xFEDCBA98&&GetLastError()==0);
  CHECK(TlsFree(tls[12]));index=TlsAlloc();CHECK(index==tls[12]&&TlsGetValue(index)==NULL);
  for(index=0;index<65;index++)CHECK(TlsFree(tls[index]));
  CHECK(!InitOnceExecuteOnce(&once,initializeOnce,(void*)0x123400,&onceContext)&&GetLastError()==123);
  CHECK(InitOnceExecuteOnce(&once,initializeOnce,(void*)0x123400,&onceContext)&&onceContext==(void*)0x123400);
  CHECK(InitOnceExecuteOnce(&once,initializeOnce,NULL,&onceContext)&&initializationCalls==2);
  InitOnceInitialize(&manual);
  CHECK(InitOnceBeginInitialize(&manual,0,&pending,&onceContext)&&pending);
  CHECK(InitOnceComplete(&manual,0,(void*)0x567800));
  CHECK(InitOnceBeginInitialize(&manual,1,&pending,&onceContext)&&!pending&&onceContext==(void*)0x567800);
  index=0;flags=1;CHECK(WaitOnAddress(&index,&flags,4,0));
  flags=0;CHECK(!WaitOnAddress(&index,&flags,4,0)&&GetLastError()==1460);
  CHECK(!WaitOnAddress(&index,&flags,3,0)&&GetLastError()==87);
  WakeByAddressSingle(&index);WakeByAddressAll(&index);
  CHECK(sizeof(critical)==24&&InitializeCriticalSectionEx(&critical,4000,0x01000000));
  CHECK(critical.lockCount==-1&&critical.recursion==0&&critical.spin==0);
  EnterCriticalSection(&critical);CHECK(TryEnterCriticalSection(&critical));
  CHECK(critical.recursion==2&&critical.owner==(HANDLE)8&&critical.lockCount==-2);
  CHECK(SetCriticalSectionSpinCount(&critical,200)==0);
  LeaveCriticalSection(&critical);LeaveCriticalSection(&critical);
  CHECK(critical.recursion==0&&critical.owner==NULL&&critical.lockCount==-1);
  DeleteCriticalSection(&critical);InitializeCriticalSection(&critical);DeleteCriticalSection(&critical);
  CHECK(InitializeCriticalSectionAndSpinCount(&critical,100));DeleteCriticalSection(&critical);
  CHECK(SetEnvironmentVariableA("B86_TEST","value"));
  DWORD srw=0;
  AcquireSRWLockShared(&srw);CHECK(!TryAcquireSRWLockExclusive(&srw));ReleaseSRWLockShared(&srw);
  AcquireSRWLockExclusive(&srw);CHECK(!TryAcquireSRWLockShared(&srw));CHECK(!TryAcquireSRWLockExclusive(&srw));ReleaseSRWLockExclusive(&srw);
  InitializeSRWLock(&srw);CHECK(TryAcquireSRWLockShared(&srw));ReleaseSRWLockShared(&srw);
  CHECK(TryAcquireSRWLockExclusive(&srw));ReleaseSRWLockExclusive(&srw);
  DWORD condition=0;
  SYSTEMTIME utc={2000,2,65535,29,23,59,59,999},converted;FILETIME stamp,epoch={0,0};
  CHECK(SystemTimeToFileTime(&utc,&stamp));CHECK(FileTimeToSystemTime(&stamp,&converted));
  CHECK(converted.year==2000&&converted.month==2&&converted.day==29&&converted.weekday==2&&converted.millis==999);
  CHECK(CompareFileTime(&epoch,&stamp)==-1&&CompareFileTime(&stamp,&epoch)==1&&CompareFileTime(&stamp,&stamp)==0);
  utc.year=1900;CHECK(!SystemTimeToFileTime(&utc,&stamp)&&GetLastError()==87);
  WORD fatDate,fatTime;
  HDC savedDC=GetDC(NULL);POINT savedPosition;
  DWORD extBrush[3]={0,0x123456,99},extDescription[6];
  HANDLE extNullPen=ExtCreatePen(0x10005,99,extBrush,0,NULL);CHECK(extNullPen==GetStockObject(8)&&GetObjectType(extNullPen)==1);
  DWORD dashStyle[3]={3,2,1},dashDescription[9];HANDLE dashPen=ExtCreatePen(0x12207,4,extBrush,3,dashStyle);
  CHECK(dashPen&&GetObjectW(dashPen,36,dashDescription)==36&&dashDescription[5]==3&&dashDescription[6]==3&&dashDescription[7]==2&&dashDescription[8]==1&&DeleteObject(dashPen));
  HANDLE extPen=ExtCreatePen(0x12200,4,extBrush,0,NULL);
  CHECK(extPen&&GetObjectType(extPen)==11&&GetObjectW(extPen,24,extDescription)==24&&extDescription[0]==0x12200&&extDescription[1]==4&&extDescription[3]==0x123456&&extDescription[4]==99&&DeleteObject(extPen));
  union {float value;DWORD bits;} miter;
  CHECK(GetMiterLimit(savedDC,&miter.value)&&miter.bits==0x41200000);
  CHECK(SetMiterLimit(savedDC,2.5f,&miter.value)&&miter.bits==0x41200000&&GetMiterLimit(savedDC,&miter.value)&&miter.bits==0x40200000);
  CHECK(!SetMiterLimit(savedDC,0.5f,NULL)&&GetLastError()==87);
  POINT shapePoints[3]={{1,1},{9,1},{5,9}};
  POINT curvePoints[4]={{1,1},{3,9},{7,9},{9,1}};BYTE curveTypes[4]={6,4,4,5};
  CHECK(PolyDraw(savedDC,curvePoints,curveTypes,4)&&GetCurrentPositionEx(savedDC,&savedPosition)&&savedPosition.x==9&&savedPosition.y==1);
  curveTypes[2]=2;CHECK(!PolyDraw(savedDC,curvePoints,curveTypes,4)&&GetLastError()==87);
  CHECK(MoveToEx(savedDC,7,8,NULL)&&PolyBezier(savedDC,curvePoints,4)&&GetCurrentPositionEx(savedDC,&savedPosition)&&savedPosition.x==7&&savedPosition.y==8);
  CHECK(PolyBezierTo(savedDC,curvePoints+1,3)&&GetCurrentPositionEx(savedDC,&savedPosition)&&savedPosition.x==9&&savedPosition.y==1);
  CHECK(!PolyBezier(savedDC,curvePoints,3)&&GetLastError()==87);
  POINT groupedPoints[4]={{1,1},{4,1},{7,7},{9,7}};DWORD groupedCounts[2]={2,2};
  CHECK(PolyPolygon(savedDC,groupedPoints,(int*)groupedCounts,2));
  CHECK(PolyPolyline(savedDC,groupedPoints,groupedCounts,2));groupedCounts[1]=1;CHECK(!PolyPolyline(savedDC,groupedPoints,groupedCounts,2)&&GetLastError()==87);
  CHECK(MoveToEx(savedDC,7,8,NULL)&&PolylineTo(savedDC,shapePoints,3));
  CHECK(GetCurrentPositionEx(savedDC,&savedPosition)&&savedPosition.x==5&&savedPosition.y==9&&PolylineTo(savedDC,NULL,0));
  CHECK(GetPolyFillMode(savedDC)==1&&SetPolyFillMode(savedDC,2)==1&&GetPolyFillMode(savedDC)==2);
  CHECK(Polygon(savedDC,shapePoints,3)&&Polyline(savedDC,shapePoints,3));
  CHECK(!Polygon(savedDC,shapePoints,1)&&GetLastError()==87);
  DWORD ansiFontData[23]={0},ansiFontCopy[15]={0};
  WORD* ansiFace=(WORD*)((BYTE*)ansiFontData+28);ansiFace[0]=0xff21;ansiFace[1]=0x100;ansiFace[2]=0x2212;ansiFace[3]=0xd83d;ansiFace[4]=0xde00;
  HANDLE ansiMappedFont=CreateFontIndirectW(ansiFontData);CHECK(ansiMappedFont&&GetObjectA(ansiMappedFont,60,ansiFontCopy)==60);
  BYTE* ansiMappedFace=(BYTE*)ansiFontCopy+28;CHECK(ansiMappedFace[0]==65&&ansiMappedFace[1]==65&&ansiMappedFace[2]==45&&ansiMappedFace[3]==63&&ansiMappedFace[4]==63&&ansiMappedFace[5]==0&&DeleteObject(ansiMappedFont));
  DWORD logicalFont[23]={0},fontCopy[23]={0};logicalFont[0]=(DWORD)-17;logicalFont[4]=700;logicalFont[7]=65;
  HANDLE fontA=CreateFontIndirectA(logicalFont),fontW=CreateFontIndirectW(logicalFont);
  CHECK(fontA&&fontW&&GetObjectW(fontA,92,fontCopy)==92&&fontCopy[0]==(DWORD)-17&&fontCopy[4]==700&&fontCopy[7]==65);
  CHECK(GetObjectA(fontW,60,fontCopy)==60&&((BYTE*)fontCopy)[28]==65&&DeleteObject(fontA)&&DeleteObject(fontW));
  RECT paintRect={1,1,4,4};HANDLE paintBrush=CreateSolidBrush(0x123456);
  CHECK(FillRect(savedDC,&paintRect,paintBrush)&&FrameRect(savedDC,&paintRect,paintBrush));
  paintRect.left=5;CHECK(!FrameRect(savedDC,&paintRect,paintBrush)&&FillRect(savedDC,&paintRect,paintBrush));
  CHECK(DeleteObject(paintBrush));
  CHECK(GetDCPenColor(savedDC)==0&&GetDCBrushColor(savedDC)==0xffffff);
  CHECK(SetDCPenColor(savedDC,0x123456)==0&&SetDCBrushColor(savedDC,0xabcdef)==0xffffff);
  CHECK(SaveDC(savedDC)==1&&SetDCPenColor(savedDC,7)==0x123456&&SetDCBrushColor(savedDC,8)==0xabcdef);
  CHECK(RestoreDC(savedDC,-1)&&GetDCPenColor(savedDC)==0x123456&&GetDCBrushColor(savedDC)==0xabcdef);
  DWORD penDescription[4],brushDescription[3];
  HANDLE systemBrush=GetSysColorBrush(8);CHECK(systemBrush&&systemBrush==GetSysColorBrush(8)&&GetObjectType(systemBrush)==2);
  CHECK(GetObjectW(systemBrush,12,brushDescription)==12&&brushDescription[0]==0&&brushDescription[1]==GetSysColor(8));
  CHECK(DeleteObject(systemBrush)&&GetSysColorBrush(8)==systemBrush&&GetObjectType(systemBrush)==2);
  CHECK(!GetSysColorBrush(-1)&&!GetSysColorBrush(31)&&!GetSysColor(-1));
  POINT brushOrigin;CHECK(GetBrushOrgEx(savedDC,&brushOrigin)&&brushOrigin.x==0&&brushOrigin.y==0);
  CHECK(SetBrushOrgEx(savedDC,19,-12,&brushOrigin)&&brushOrigin.x==0&&brushOrigin.y==0);
  CHECK(SaveDC(savedDC)==1&&SetBrushOrgEx(savedDC,8,9,NULL)&&RestoreDC(savedDC,-1));
  CHECK(GetBrushOrgEx(savedDC,&brushOrigin)&&brushOrigin.x==19&&brushOrigin.y==-12);
  CHECK(!GetBrushOrgEx(savedDC,NULL)&&GetLastError()==87);
  for(int style=1;style<=4;style++){
    HANDLE widePen=CreatePen(style,-3,0x123456);CHECK(widePen&&GetObjectW(widePen,16,penDescription)==16&&penDescription[0]==(DWORD)style&&penDescription[1]==3);
    CHECK(DeleteObject(widePen));
    DWORD wideData[4]={(DWORD)style,2,99,0x123456};widePen=CreatePenIndirect(wideData);
    CHECK(widePen&&GetObjectA(widePen,16,penDescription)==16&&penDescription[0]==(DWORD)style&&penDescription[1]==2&&penDescription[2]==0);CHECK(DeleteObject(widePen));
  }
  DWORD indirectPenData[4]={0,(DWORD)-3,99,0x123456},indirectBrushData[3]={1,0xabcdef,99};
  HANDLE indirectPen=CreatePenIndirect(indirectPenData),indirectBrush=CreateBrushIndirect(indirectBrushData);
  CHECK(indirectPen&&indirectBrush&&GetObjectW(indirectPen,16,penDescription)==16&&penDescription[1]==3&&penDescription[2]==0&&penDescription[3]==0x123456);
  CHECK(GetObjectA(indirectBrush,12,brushDescription)==12&&brushDescription[0]==1&&brushDescription[1]==0&&brushDescription[2]==0);
  CHECK(DeleteObject(indirectPen)&&DeleteObject(indirectBrush));
  CHECK(GetObjectA(GetCurrentObject(savedDC,1),0,NULL)==16);
  CHECK(GetObjectW(GetCurrentObject(savedDC,1),16,penDescription)==16&&penDescription[0]==0&&penDescription[1]==1&&penDescription[2]==0&&penDescription[3]==0);
  CHECK(GetObjectA(GetCurrentObject(savedDC,2),12,brushDescription)==12&&brushDescription[0]==0&&brushDescription[1]==0xffffff&&brushDescription[2]==0);
  CHECK(!GetObjectW(GetCurrentObject(savedDC,1),15,penDescription));
  CHECK(GetTextColor(savedDC)==0&&GetBkColor(savedDC)==0xffffff&&GetBkMode(savedDC)==2&&GetTextAlign(savedDC)==0);
  CHECK(GetObjectType(savedDC)==3&&GetObjectType(GetCurrentObject(savedDC,1))==1&&GetObjectType(GetCurrentObject(savedDC,2))==2&&GetObjectType(GetCurrentObject(savedDC,6))==6);
  CHECK(GetTextColor(NULL)==0xffffffff&&GetBkMode(NULL)==0&&!GetCurrentObject(savedDC,99)&&GetLastError()==87);
  CHECK(savedDC&&MoveToEx(savedDC,3,4,NULL)&&SaveDC(savedDC)==1);
  CHECK(MoveToEx(savedDC,10,20,NULL)&&SaveDC(savedDC)==2&&MoveToEx(savedDC,30,40,NULL));
  CHECK(RestoreDC(savedDC,-1)&&GetCurrentPositionEx(savedDC,&savedPosition)&&savedPosition.x==10&&savedPosition.y==20);
  CHECK(RestoreDC(savedDC,1)&&GetCurrentPositionEx(savedDC,&savedPosition)&&savedPosition.x==3&&savedPosition.y==4);
  CHECK(!RestoreDC(savedDC,-1)&&GetLastError()==87);CHECK(ReleaseDC(NULL,savedDC));
  RECT regionInput={10,20,1,2},regionBox;HANDLE regionA=CreateRectRgn(1,2,10,20),regionB=CreateRectRgnIndirect(&regionInput);
  CHECK(regionA&&regionB&&EqualRgn(regionA,regionB)&&GetObjectType(regionA)==8);
  CHECK(GetRgnBox(regionA,&regionBox)==2&&regionBox.left==1&&regionBox.bottom==20&&PtInRegion(regionA,1,2)&&!PtInRegion(regionA,10,20));
  CHECK(RectInRegion(regionA,&regionInput));regionInput.left=10;regionInput.right=10;regionInput.top=20;regionInput.bottom=20;CHECK(RectInRegion(regionA,&regionInput));
  regionInput.left=10;regionInput.right=11;regionInput.top=2;regionInput.bottom=20;CHECK(!RectInRegion(regionA,&regionInput));
  CHECK(OffsetRgn(regionB,2,-1)==2&&!EqualRgn(regionA,regionB));
  CHECK(SetRectRgn(regionB,3,4,3,8)&&GetRgnBox(regionB,&regionBox)==1&&regionBox.left==0&&regionBox.bottom==0);
  CHECK(!GetClipRgn(savedDC,regionB)&&SelectClipRgn(savedDC,regionA)==2&&GetClipRgn(savedDC,regionB)==1&&EqualRgn(regionA,regionB));
  CHECK(SaveDC(savedDC)==1&&OffsetClipRgn(savedDC,2,-1)==2&&GetClipBox(savedDC,&regionBox)==2&&regionBox.left==3&&regionBox.top==1&&RestoreDC(savedDC,-1));
  CHECK(SaveDC(savedDC)==1&&IntersectClipRect(savedDC,2,3,8,9)!=0&&GetClipBox(savedDC,&regionBox)==2&&regionBox.left==2&&regionBox.bottom==9&&RestoreDC(savedDC,-1));
  CHECK(GetClipBox(savedDC,&regionBox)==2&&regionBox.left==1&&regionBox.bottom==20&&PtVisible(savedDC,1,2)&&!PtVisible(savedDC,10,20)&&RectVisible(savedDC,&regionBox));
  CHECK(SaveDC(savedDC)==1&&SelectClipRgn(savedDC,NULL)==2&&RestoreDC(savedDC,-1)&&GetClipRgn(savedDC,regionB)==1);
  CHECK(SelectClipRgn(savedDC,NULL)==2&&SetRectRgn(regionB,0,0,0,0));
  CHECK(InvertRect(savedDC,&regionInput)&&InvertRect(savedDC,&regionInput));
  RECT extremeInvert={(int)0x80000000,1,7,7};CHECK(InvertRect(savedDC,&extremeInvert)&&InvertRect(savedDC,&extremeInvert));
  CHECK(InvertRgn(savedDC,regionA)&&InvertRgn(savedDC,regionA)&&InvertRgn(savedDC,regionB));
  CHECK(FrameRgn(savedDC,regionA,GetStockObject(4),-2,1)&&!FrameRgn(savedDC,regionA,GetStockObject(4),0,1));
  CHECK(FillRgn(savedDC,regionA,GetStockObject(4))&&PaintRgn(savedDC,regionA));
  CHECK(!FillRgn(savedDC,regionA,NULL)&&FillRgn(savedDC,regionB,GetStockObject(5)));
  DWORD regionData[12];CHECK(GetRegionData(regionA,0,NULL)==48&&GetRegionData(regionA,48,regionData)==48);
  CHECK(regionData[0]==32&&regionData[1]==1&&regionData[2]==1&&regionData[3]==16&&regionData[8]==1&&regionData[11]==20);
  CHECK(!GetRegionData(regionA,47,regionData)&&GetLastError()==87);
  CHECK(GetRegionData(regionB,48,regionData)==32&&regionData[2]==0&&regionData[3]==0);
  CHECK(!RectInRegion(regionB,NULL));CHECK(DeleteObject(regionA)&&DeleteObject(regionB));
  WNDCLASSA rejectClass={0};rejectClass.proc=rejectProc;rejectClass.name="RejectFixture";CHECK(RegisterClassA(&rejectClass));
  rejectStage=129;CHECK(!CreateWindowExA(0,"RejectFixture","",0x80000000,0,0,20,20,NULL,NULL,NULL,NULL));
  CHECK(rejectCount==2&&rejectLog[0]==129&&rejectLog[1]==130&&!IsWindow(rejectedWindow));
  rejectStage=1;rejectCount=0;CHECK(!CreateWindowExA(0,"RejectFixture","",0x80000000,0,0,20,20,NULL,NULL,NULL,NULL));
  CHECK(rejectCount==4&&rejectLog[0]==129&&rejectLog[1]==1&&rejectLog[2]==2&&rejectLog[3]==130&&!IsWindow(rejectedWindow));
  WNDCLASSA lifetimeClass={0};lifetimeClass.proc=lifetimeProc;lifetimeClass.name="LifetimeFixture";CHECK(RegisterClassA(&lifetimeClass));
  lifetimeWindows[0]=CreateWindowExA(0,"LifetimeFixture","",0x80000000,0,0,20,20,NULL,NULL,NULL,NULL);
  lifetimeWindows[1]=CreateWindowExA(0,"LifetimeFixture","",0x40000000,0,0,20,20,lifetimeWindows[0],NULL,NULL,NULL);
  lifetimeWindows[2]=CreateWindowExA(0,"LifetimeFixture","",0x40000000,0,0,20,20,lifetimeWindows[1],NULL,NULL,NULL);
  lifetimeWindows[3]=CreateWindowExA(0,"LifetimeFixture","",0x80000000,0,0,20,20,lifetimeWindows[1],NULL,NULL,NULL);
  for(int i=0;i<4;i++)CHECK(lifetimeWindows[i]&&IsWindow(lifetimeWindows[i]));
  DWORD windowProcessId=0;CHECK(GetWindowThreadProcessId(lifetimeWindows[0],&windowProcessId)==GetCurrentThreadId()&&windowProcessId==GetCurrentProcessId());
  CHECK(GetWindowThreadProcessId(lifetimeWindows[1],NULL)==GetCurrentThreadId()&&!IsWindowUnicode(lifetimeWindows[0]));
  SetLastError(1234);CHECK(!GetWindowThreadProcessId(NULL,&windowProcessId)&&GetLastError()==1400&&windowProcessId==GetCurrentProcessId());
  CHECK(IsWindowEnabled(lifetimeWindows[0])&&!IsWindowVisible(lifetimeWindows[0]));
  CHECK(!EnableWindow(lifetimeWindows[0],0)&&!IsWindowEnabled(lifetimeWindows[0])&&IsWindowEnabled(lifetimeWindows[1]));
  CHECK(EnableWindow(lifetimeWindows[0],0));CHECK(EnableWindow(lifetimeWindows[0],1));CHECK(!EnableWindow(lifetimeWindows[0],1));
  CHECK(enableCount==4&&enableLog[0]==31&&enableState[0]==1&&enableLog[1]==10&&enableState[1]==0&&enableLog[2]==31&&enableState[2]==0&&enableLog[3]==10&&enableState[3]==1);
  CHECK(GetParent(lifetimeWindows[2])==lifetimeWindows[1]&&GetParent(lifetimeWindows[3])==lifetimeWindows[0]);
  CHECK(IsChild(lifetimeWindows[0],lifetimeWindows[2])&&!IsChild(lifetimeWindows[0],lifetimeWindows[3])&&!IsChild(lifetimeWindows[0],lifetimeWindows[0]));
  WORD atomWide[]={ 'M','I','X','E','D',0 },atomOutput[16];char atomAnsi[16];
  SetLastError(1234);CHECK(InitAtomTable(37)&&GetLastError()==1234);
  WORD localAtom=AddAtomA("MiXeD");CHECK(localAtom>=0xc000&&AddAtomW(atomWide)==localAtom&&FindAtomW(atomWide)==localAtom);
  CHECK(InitAtomTable(0xffffffff)&&FindAtomA("mixed")==localAtom);
  CHECK(GetAtomNameA(localAtom,atomAnsi,3)==2&&atomAnsi[0]=='M'&&atomAnsi[1]=='i'&&!atomAnsi[2]);
  CHECK(GetAtomNameW(localAtom,atomOutput,16)==5&&atomOutput[0]=='M'&&atomOutput[1]=='i'&&atomOutput[2]=='X'&&atomOutput[3]=='e'&&atomOutput[4]=='D'&&!atomOutput[5]);
  CHECK(!DeleteAtom(localAtom)&&FindAtomA("mixed")==localAtom);CHECK(!DeleteAtom(localAtom));SetLastError(1234);CHECK(!FindAtomA("mixed")&&GetLastError()==2);
  CHECK(AddAtomA("#0001")==1&&FindAtomW((const WORD*)1)==1&&GetAtomNameA(1,atomAnsi,16)==2&&atomAnsi[0]=='#'&&atomAnsi[1]=='1');
  WORD globalWide[]={ 'G','l','o','b','a','l','C','o','n','t','e','x','t',0 };
  WORD globalAtom=GlobalAddAtomA("GlobalContext");CHECK(globalAtom>=0xc000&&GlobalAddAtomW(globalWide)==globalAtom&&GlobalFindAtomW(globalWide)==globalAtom);
  CHECK(SetPropA(lifetimeWindows[0],(const char*)(DWORD)globalAtom,(HANDLE)789)&&GetPropW(lifetimeWindows[0],globalWide)==(HANDLE)789);
  CHECK(GlobalGetAtomNameW(globalAtom,atomOutput,3)==3&&atomOutput[0]=='G'&&atomOutput[1]=='l'&&atomOutput[2]=='o');
  SetLastError(1234);CHECK(!GlobalGetAtomNameA(globalAtom,atomAnsi,3)&&GetLastError()==234&&atomAnsi[0]=='G'&&atomAnsi[1]=='l'&&!atomAnsi[2]);
  CHECK(RemovePropW(lifetimeWindows[0],globalWide)==(HANDLE)789);CHECK(!GlobalDeleteAtom(globalAtom)&&GlobalFindAtomA("GlobalContext")==globalAtom);CHECK(!GlobalDeleteAtom(globalAtom));
  CHECK(!GlobalFindAtomA("GlobalContext"));
  WORD extendedAtom=GlobalAddAtomExA("GlobalContext",0);CHECK(extendedAtom&&GlobalAddAtomExW(globalWide,2)==extendedAtom);
  SetLastError(1234);CHECK(!GlobalAddAtomExA("GlobalContext",4)&&GetLastError()==87);CHECK(GlobalAddAtomExW((const WORD*)1,0xffffffff)==1);
  CHECK(!GlobalDeleteAtom(extendedAtom)&&GlobalFindAtomA("GlobalContext")==extendedAtom);CHECK(!GlobalDeleteAtom(extendedAtom)&&!GlobalFindAtomA("GlobalContext"));
  WORD propertyName[]={ 'C','o','n','t','e','x','t',0 };
  CHECK(SetPropA(lifetimeWindows[0],"context",(HANDLE)0x12345678));CHECK(GetPropW(lifetimeWindows[0],propertyName)==(HANDLE)0x12345678);
  CHECK(SetPropW(lifetimeWindows[0],propertyName,(HANDLE)0xffffffff));CHECK(RemovePropA(lifetimeWindows[0],"CONTEXT")== (HANDLE)0xffffffff);
  CHECK(SetPropA(lifetimeWindows[0],"#0001",(HANDLE)123));CHECK(GetPropA(lifetimeWindows[0],(const char*)1)==(HANDLE)123);CHECK(RemovePropW(lifetimeWindows[0],(const WORD*)1)==(HANDLE)123);
  CHECK(SetPropW(lifetimeWindows[0],propertyName,NULL));SetLastError(1234);CHECK(!GetPropA(lifetimeWindows[0],"context")&&GetLastError()==1234);CHECK(!RemovePropW(lifetimeWindows[0],propertyName));
  CHECK(SetPropA(lifetimeWindows[0],"Enumerated",(HANDLE)17));CHECK(SetPropA(lifetimeWindows[0],(const char*)5,(HANDLE)23));
  CHECK(EnumPropsA(lifetimeWindows[0],enumPropertyA)==7&&propertyEnumCount==2&&propertyEnumSum==40);
  propertyEnumCount=propertyEnumSum=0;CHECK(EnumPropsW(lifetimeWindows[0],enumPropertyW)==7&&propertyEnumCount==2&&propertyEnumSum==40);
  CHECK(EnumPropsExA(lifetimeWindows[0],enumPropertyExA,0xabcdef12)==0);
  propertyEnumCount=0;CHECK(EnumPropsExW(lifetimeWindows[0],enumPropertyExW,99)==7&&propertyEnumCount==2);
  CHECK(EnumPropsA(lifetimeWindows[0],enumPropertyA)==-1);
  CHECK(!SetFocus(lifetimeWindows[1])&&GetFocus()==lifetimeWindows[1]);
  CHECK(SetFocus(lifetimeWindows[2])==lifetimeWindows[1]&&GetFocus()==lifetimeWindows[2]);
  CHECK(SetFocus(lifetimeWindows[2])==lifetimeWindows[2]);CHECK(SetFocus(NULL)==lifetimeWindows[2]&&!GetFocus());
  CHECK(focusCount==4&&focusMessages[0]==7&&focusMessages[1]==8&&focusMessages[2]==7&&focusMessages[3]==8);
  CHECK(focusObserved[0]==lifetimeWindows[1]&&focusObserved[1]==lifetimeWindows[2]&&focusObserved[2]==lifetimeWindows[2]&&!focusObserved[3]);
  CHECK(!focusOther[0]&&focusOther[1]==lifetimeWindows[2]&&focusOther[2]==lifetimeWindows[1]&&!focusOther[3]);
  CHECK(!SetFocus(lifetimeWindows[1]));CHECK(!EnableWindow(lifetimeWindows[1],0)&&!GetFocus());
  CHECK(focusCount==6&&focusMessages[5]==8&&!focusObserved[5]);
  SetLastError(1234);CHECK(!SetFocus(lifetimeWindows[2])&&GetLastError()==87);
  CHECK(DestroyWindow(lifetimeWindows[0]));CHECK(lifetimeCount==8);
  DWORD expectedLifetime[8]={770,898,2,258,514,642,386,130};
  for(int i=0;i<8;i++)CHECK(lifetimeLog[i]==expectedLifetime[i]);
  for(int i=0;i<4;i++)CHECK(!IsWindow(lifetimeWindows[i]));
  HWND coordinateWindow=CreateWindowExA(0,"STATIC","",0x80000000,40,50,100,100,NULL,NULL,NULL,NULL);
  HWND coordinateChild=CreateWindowExA(0,"STATIC","",0x40000000,7,9,20,20,coordinateWindow,NULL,NULL,NULL);POINT coordinatePoint={0,0};
  CHECK(coordinateWindow&&coordinateChild&&ClientToScreen(coordinateChild,&coordinatePoint)&&coordinatePoint.x==47&&coordinatePoint.y==59);
  CHECK(ScreenToClient(coordinateChild,&coordinatePoint)&&coordinatePoint.x==0&&coordinatePoint.y==0);
  CHECK(MapWindowPoints(coordinateChild,NULL,&coordinatePoint,1)==0x003b002f&&coordinatePoint.x==47&&coordinatePoint.y==59);RECT coordinateRect;CHECK(GetWindowRect(coordinateChild,&coordinateRect)&&coordinateRect.left==47&&coordinateRect.top==59&&coordinateRect.right==67&&coordinateRect.bottom==79);
  CHECK(GetClientRect(coordinateChild,&coordinateRect)&&coordinateRect.left==0&&coordinateRect.top==0&&coordinateRect.right==20&&coordinateRect.bottom==20);
  SetLastError(1234);CHECK(!GetWindowRect(coordinateChild,NULL)&&GetLastError()==1400);CHECK(DestroyWindow(coordinateWindow));
  RECT rectA,rectB,rectOut;POINT rectPoint={0,0};
  CHECK(SetRect(&rectA,0,0,10,10)&&SetRect(&rectB,0,0,5,10));
  CHECK(PtInRect(&rectA,rectPoint));rectPoint.x=10;CHECK(!PtInRect(&rectA,rectPoint));
  CHECK(SubtractRect(&rectOut,&rectA,&rectB)&&rectOut.left==5);
  CHECK(IntersectRect(&rectOut,&rectA,&rectB)&&EqualRect(&rectOut,&rectB));
  CHECK(UnionRect(&rectOut,&rectA,&rectB)&&EqualRect(&rectOut,&rectA));
  CHECK(CopyRect(&rectOut,&rectB)&&OffsetRect(&rectOut,1,2)&&InflateRect(&rectOut,1,2)&&rectOut.left==0&&rectOut.right==7);
  CHECK(SetRectEmpty(&rectOut)&&IsRectEmpty(&rectOut));
  CHECK(MulDiv(5,3,2)==8&&MulDiv(-5,3,2)==-8&&MulDiv(5,3,-2)==-8);
  CHECK(MulDiv(2147483647,2147483647,2147483647)==2147483647);
  CHECK(MulDiv(1,1,0)==-1&&MulDiv(2147483647,2,1)==-1&&MulDiv((int)0x80000000,1,2)==-1);
  WORD shellLine[]={'p',' ','"','a',' ','b','"',' ','c',0};int shellCount=0;
  WORD** shellArgs=CommandLineToArgvW(shellLine,&shellCount);
  CHECK(shellArgs&&shellCount==3&&shellArgs[1][0]=='a'&&shellArgs[1][1]==' '&&shellArgs[1][2]=='b'&&shellArgs[2][0]=='c');
  CHECK(LocalFree(shellArgs)==NULL);
  WORD typedText[]={'A','0',' ',0},charTypes[4];
  CHECK(GetStringTypeW(1,typedText,-1,charTypes)&&(charTypes[0]&0x101)==0x101&&(charTypes[1]&4)&&(charTypes[2]&8)&&(charTypes[3]&0x20));
  CHECK(GetStringTypeW(2,typedText,3,charTypes)&&charTypes[0]==1&&charTypes[1]==3&&charTypes[2]==10);
  CHECK(GetStringTypeW(4,typedText,3,charTypes)&&(charTypes[0]&0x8000));
  CHECK(!GetStringTypeW(3,typedText,3,charTypes)&&GetLastError()==1004);
  CPINFO cpInfo;CPINFOEXA cpInfoA;CPINFOEXW cpInfoW;
  CHECK(sizeof(CPINFO)==20&&sizeof(CPINFOEXA)==284&&sizeof(CPINFOEXW)==544);
  CHECK(IsValidCodePage(65001)&&!IsValidCodePage(0));
  CHECK(GetCPInfo(65001,&cpInfo)&&cpInfo.maxCharSize==4&&cpInfo.defaultChar[0]=='?');
  CHECK(GetCPInfoExA(0,0,&cpInfoA)&&cpInfoA.codePage==1252&&cpInfoA.name[0]=='1');
  CHECK(GetCPInfoExW(65001,0,&cpInfoW)&&cpInfoW.unicodeDefault==0xfffd&&cpInfoW.name[0]=='6');
  CHECK(!GetCPInfoExA(1252,1,&cpInfoA)&&GetLastError()==1004);
  const char utf8Bom[]={ (char)0xef,(char)0xbb,(char)0xbf,'A',0 };WORD decoded[8];char encoded[16];
  CHECK(MultiByteToWideChar(65001,8,utf8Bom,-1,decoded,8)==3&&decoded[0]==0xfeff&&decoded[1]=='A');
  CHECK(WideCharToMultiByte(65001,0x80,decoded,3,encoded,16,NULL,NULL)==5&&encoded[0]==(char)0xef);
  decoded[0]=0xd800;CHECK(!WideCharToMultiByte(65001,0x80,decoded,1,encoded,16,NULL,NULL)&&GetLastError()==1113);
  BOOL usedFallback=0;WORD legacyText[]={0x221e,0};
  CHECK(WideCharToMultiByte(1252,0,legacyText,1,encoded,16,NULL,&usedFallback)==1&&encoded[0]=='8'&&!usedFallback);
  CHECK(WideCharToMultiByte(1252,0x400,legacyText,1,encoded,16,"!",&usedFallback)==1&&encoded[0]=='!'&&usedFallback);
  CHECK(WideCharToMultiByte(437,0,legacyText,1,encoded,16,NULL,NULL)==1&&(BYTE)encoded[0]==0xec);
  CHECK(MultiByteToWideChar(1,0,encoded,1,decoded,8)==1&&decoded[0]==0x221e);
  WORD ordinalA[]={'A',0,'x',0},ordinalB[]={'a',0,'y',0};
  CHECK(CompareStringOrdinal(ordinalA,-1,ordinalB,-1,1)==2);
  CHECK(CompareStringOrdinal(ordinalA,3,ordinalB,3,1)==1);
  CHECK(CompareStringOrdinal(ordinalA,1,ordinalB,1,0)==1);
  CHECK(!CompareStringOrdinal(ordinalA,1,ordinalB,1,2)&&GetLastError()==87);
  WORD searchSource[]={'a','b','A','B',0},searchValue[]={'a','b',0};
  CHECK(FindStringOrdinal(0,searchSource,-1,searchValue,-1,1)==0);
  CHECK(FindStringOrdinal(0x800000,searchSource,-1,searchValue,-1,1)==2);
  CHECK(FindStringOrdinal(0x100000,searchSource,-1,searchValue,-1,1)==0);
  CHECK(FindStringOrdinal(0x200000,searchSource,-1,searchValue,-1,0)==-1&&GetLastError()==0);
  CHECK(FindStringOrdinal(1,searchSource,-1,searchValue,-1,0)==-1&&GetLastError()==1004);
  CHECK(DosDateTimeToFileTime(0x21,0,&stamp));CHECK(FileTimeToDosDateTime(&stamp,&fatDate,&fatTime));
  CHECK(fatDate==0x21&&fatTime==0);stamp.low++;
  CHECK(FileTimeToDosDateTime(&stamp,&fatDate,&fatTime)&&fatTime==1);
  CHECK(!DosDateTimeToFileTime(0,0,&stamp)&&GetLastError()==87);
  InitializeConditionVariable(&condition);WakeConditionVariable(&condition);WakeAllConditionVariable(&condition);
  AcquireSRWLockExclusive(&srw);CHECK(!SleepConditionVariableSRW(&condition,&srw,0,0)&&GetLastError()==1460);ReleaseSRWLockExclusive(&srw);
  AcquireSRWLockShared(&srw);CHECK(!SleepConditionVariableSRW(&condition,&srw,0,1)&&GetLastError()==1460);ReleaseSRWLockShared(&srw);
  InitializeCriticalSection(&critical);EnterCriticalSection(&critical);
  CHECK(!SleepConditionVariableCS(&condition,&critical,0)&&GetLastError()==1460);
  CHECK(critical.recursion==1&&critical.owner!=NULL);LeaveCriticalSection(&critical);DeleteCriticalSection(&critical);
  CHECK(GetEnvironmentVariableA("b86_test",finalPath,256)==5&&finalPath[0]=='v');
  CHECK(ExpandEnvironmentStringsA("[%B86_TEST%]",finalPath,256)==8&&finalPath[0]=='['&&finalPath[6]==']');
  CHECK(SetEnvironmentVariableA("B86_TEST",""));
  CHECK(GetEnvironmentVariableA("B86_TEST",NULL,0)==1);
  CHECK(GetEnvironmentVariableA("B86_TEST",finalPath,256)==0&&finalPath[0]==0);
  CHECK(FreeEnvironmentStringsA(GetEnvironmentStrings()));
  CHECK(FreeEnvironmentStringsW(GetEnvironmentStringsW()));
  CHECK(SetEnvironmentVariableA("B86_TEST",NULL));
  CHECK(GetEnvironmentVariableA("B86_TEST",finalPath,256)==0&&GetLastError()==203);
  CHECK(DuplicateHandle(self,self,self,&process,0,0,2));
  CHECK(DuplicateHandle(self,GetCurrentThread(),self,&thread,0,0,2));
  CHECK(GetProcessId(process)==4&&GetThreadId(thread)==8);
  CHECK(GetExitCodeProcess(process,&code)&&code==259);
  CHECK(GetExitCodeThread(thread,&code)&&code==259);
  CHECK(WaitForSingleObject(thread,0)==258);
  CHECK(CloseHandle(process)&&CloseHandle(thread));
  puts("Handle checks passed.");
  ExitProcess(0);
}
