/* Original minimal declarations for these demos. No Windows SDK files shipped. */
#ifndef BROWSER86_MINWIN_H
#define BROWSER86_MINWIN_H
#define API __declspec(dllimport)
#define WINAPI __stdcall
#define NULL ((void*)0)
typedef unsigned int DWORD;typedef int BOOL;typedef void* HANDLE;typedef HANDLE HWND;typedef HANDLE HDC;typedef unsigned short WORD;typedef unsigned char BYTE;
typedef struct {DWORD low,high;} FILETIME;
typedef struct {WORD year,month,weekday,day,hour,minute,second,millis;} SYSTEMTIME;
API BOOL WINAPI FileTimeToSystemTime(const FILETIME*,SYSTEMTIME*);
API BOOL WINAPI SystemTimeToFileTime(const SYSTEMTIME*,FILETIME*);
API long WINAPI CompareFileTime(const FILETIME*,const FILETIME*);
API int WINAPI CompareStringOrdinal(const WORD*,int,const WORD*,int,BOOL);
API BOOL WINAPI GetStringTypeW(DWORD,const WORD*,int,WORD*);
API int WINAPI MulDiv(int,int,int);
API HANDLE WINAPI CreateFontIndirectA(const void*);
API HANDLE WINAPI CreateFontIndirectW(const void*);
API int WINAPI GetObjectA(HANDLE,int,void*);
API int WINAPI GetObjectW(HANDLE,int,void*);
API DWORD WINAPI GetDCPenColor(HDC);
API DWORD WINAPI SetDCPenColor(HDC,DWORD);
API DWORD WINAPI GetDCBrushColor(HDC);
API DWORD WINAPI SetDCBrushColor(HDC,DWORD);
API BOOL WINAPI PolyDraw(HDC,const void*,const BYTE*,int);
API BOOL WINAPI PolyBezier(HDC,const void*,DWORD);
API BOOL WINAPI PolyBezierTo(HDC,const void*,DWORD);
API BOOL WINAPI Polygon(HDC,const void*,int);
API BOOL WINAPI Polyline(HDC,const void*,int);
API BOOL WINAPI PolylineTo(HDC,const void*,DWORD);
API BOOL WINAPI PolyPolyline(HDC,const void*,const DWORD*,DWORD);
API BOOL WINAPI PolyPolygon(HDC,const void*,const int*,int);
API int WINAPI GetPolyFillMode(HDC);
API int WINAPI SetPolyFillMode(HDC,int);
API BOOL WINAPI GetMiterLimit(HDC,float*);
API BOOL WINAPI SetMiterLimit(HDC,float,float*);
API DWORD WINAPI GetSysColor(int);
API HANDLE WINAPI GetSysColorBrush(int);
API HANDLE WINAPI CreateRectRgn(int,int,int,int);
API HANDLE WINAPI CreateRectRgnIndirect(const void*);
API BOOL WINAPI SetRectRgn(HANDLE,int,int,int,int);
API int WINAPI GetRgnBox(HANDLE,void*);
API BOOL WINAPI PtInRegion(HANDLE,int,int);
API BOOL WINAPI RectInRegion(HANDLE,const void*);
API DWORD WINAPI GetRegionData(HANDLE,DWORD,void*);
API int WINAPI OffsetClipRgn(HDC,int,int);
API int WINAPI IntersectClipRect(HDC,int,int,int,int);
API int WINAPI GetClipBox(HDC,void*);
API BOOL WINAPI PtVisible(HDC,int,int);
API BOOL WINAPI RectVisible(HDC,const void*);
API int WINAPI SelectClipRgn(HDC,HANDLE);
API int WINAPI GetClipRgn(HDC,HANDLE);
API BOOL WINAPI ClientToScreen(HWND,void*);
API BOOL WINAPI ScreenToClient(HWND,void*);
API int WINAPI MapWindowPoints(HWND,HWND,void*,DWORD);
API BOOL WINAPI InvertRect(HDC,const void*);
API BOOL WINAPI InvertRgn(HDC,HANDLE);
API BOOL WINAPI FrameRgn(HDC,HANDLE,HANDLE,int,int);
API BOOL WINAPI FillRgn(HDC,HANDLE,HANDLE);
API BOOL WINAPI PaintRgn(HDC,HANDLE);
API BOOL WINAPI EqualRgn(HANDLE,HANDLE);
API int WINAPI OffsetRgn(HANDLE,int,int);
API int WINAPI SaveDC(HDC);
API DWORD WINAPI GetTextColor(HDC);
API DWORD WINAPI GetBkColor(HDC);
API int WINAPI GetBkMode(HDC);
API DWORD WINAPI GetTextAlign(HDC);
API HANDLE WINAPI GetCurrentObject(HDC,DWORD);
API DWORD WINAPI GetObjectType(HANDLE);
API BOOL WINAPI RestoreDC(HDC,int);
API BOOL WINAPI GetCurrentPositionEx(HDC,void*);
API BOOL WINAPI GetBrushOrgEx(HDC,void*);
API BOOL WINAPI SetBrushOrgEx(HDC,int,int,void*);
API HDC WINAPI GetDC(HWND);
API int WINAPI ReleaseDC(HWND,HDC);
API WORD** WINAPI CommandLineToArgvW(const WORD*,int*);
API void* WINAPI LocalFree(void*);
typedef struct {DWORD maxCharSize;BYTE defaultChar[2],leadByte[12];} CPINFO;
typedef struct {DWORD maxCharSize;BYTE defaultChar[2],leadByte[12];WORD unicodeDefault;DWORD codePage;char name[260];} CPINFOEXA;
typedef struct {DWORD maxCharSize;BYTE defaultChar[2],leadByte[12];WORD unicodeDefault;DWORD codePage;WORD name[260];} CPINFOEXW;
API BOOL WINAPI IsValidCodePage(DWORD);
API BOOL WINAPI GetCPInfo(DWORD,CPINFO*);
API BOOL WINAPI GetCPInfoExA(DWORD,DWORD,CPINFOEXA*);
API BOOL WINAPI GetCPInfoExW(DWORD,DWORD,CPINFOEXW*);
API int WINAPI FindStringOrdinal(DWORD,const WORD*,int,const WORD*,int,BOOL);
API int WINAPI MultiByteToWideChar(DWORD,DWORD,const char*,int,WORD*,int);
API int WINAPI WideCharToMultiByte(DWORD,DWORD,const WORD*,int,char*,int,const char*,BOOL*);
API BOOL WINAPI DosDateTimeToFileTime(WORD,WORD,FILETIME*);
API BOOL WINAPI FileTimeToDosDateTime(const FILETIME*,WORD*,WORD*);
typedef struct {DWORD attributes;FILETIME creation,access,write;DWORD volume,sizeHigh,sizeLow,links,idHigh,idLow;} BY_HANDLE_FILE_INFORMATION;
typedef struct {long long allocationSize,endOfFile;DWORD links;BYTE deletePending,directory;} FILE_STANDARD_INFO;
typedef struct {unsigned long long volume;BYTE id[16];} FILE_ID_INFO;
typedef struct {DWORD attributes,reparseTag;} FILE_ATTRIBUTE_TAG_INFO;
typedef struct {DWORD length;WORD name[128];} FILE_NAME_BUFFER;
typedef struct {BYTE replace;HANDLE root;DWORD length;WORD name[128];} FILE_RENAME_BUFFER;
typedef long (WINAPI *WNDPROC)(HWND,DWORD,DWORD,long);
typedef struct {DWORD style;WNDPROC proc;int classExtra,windowExtra;HANDLE instance,icon,cursor,brush;const char *menu,*name;} WNDCLASSA;
typedef struct {DWORD style;WNDPROC proc;int classExtra,windowExtra;HANDLE instance,icon,cursor,brush;const WORD *menu,*name;} WNDCLASSW;
typedef struct {HWND hwnd;DWORD message,wParam;long lParam;DWORD time;long x,y;} MSG;
typedef struct {HDC dc;BOOL erase;long left,top,right,bottom;BOOL restore,update;BYTE reserved[32];} PAINTSTRUCT;
typedef struct {long left,top,right,bottom;} RECT;
typedef struct {long x,y;} POINT;
API BOOL WINAPI SetRect(RECT*,int,int,int,int);
API BOOL WINAPI SetRectEmpty(RECT*);
API BOOL WINAPI CopyRect(RECT*,const RECT*);
API BOOL WINAPI EqualRect(const RECT*,const RECT*);
API BOOL WINAPI IsRectEmpty(const RECT*);
API BOOL WINAPI PtInRect(const RECT*,POINT);
API BOOL WINAPI OffsetRect(RECT*,int,int);
API BOOL WINAPI InflateRect(RECT*,int,int);
API BOOL WINAPI IntersectRect(RECT*,const RECT*,const RECT*);
API BOOL WINAPI UnionRect(RECT*,const RECT*,const RECT*);
API BOOL WINAPI SubtractRect(RECT*,const RECT*,const RECT*);
typedef struct {DWORD size;long width,height;WORD planes,bits;DWORD compression,imageSize;long xppm,yppm;DWORD colorsUsed,important;} BITMAPINFOHEADER;
API HANDLE WINAPI GetStdHandle(DWORD);
API BOOL WINAPI WriteFile(HANDLE,const void*,DWORD,DWORD*,void*);
API BOOL WINAPI ReadFile(HANDLE,void*,DWORD,DWORD*,void*);
API void WINAPI ExitProcess(DWORD);
API HANDLE WINAPI CreateFileA(const char*,DWORD,DWORD,void*,DWORD,DWORD,HANDLE);
API BOOL WINAPI DeleteFileA(const char*);
API BOOL WINAPI CreateDirectoryA(const char*,void*);
API BOOL WINAPI RemoveDirectoryA(const char*);
API BOOL WINAPI MoveFileA(const char*,const char*);
API DWORD WINAPI GetTempFileNameA(const char*,const char*,DWORD,char*);
API DWORD WINAPI GetTempFileNameW(const WORD*,const WORD*,DWORD,WORD*);
API BOOL WINAPI CloseHandle(HANDLE);
API HANDLE WINAPI GetCurrentProcess(void);
API HANDLE WINAPI GetCurrentThread(void);
API BOOL WINAPI DuplicateHandle(HANDLE,HANDLE,HANDLE,HANDLE*,DWORD,BOOL,DWORD);
API BOOL WINAPI GetHandleInformation(HANDLE,DWORD*);
API BOOL WINAPI SetHandleInformation(HANDLE,DWORD,DWORD);
API DWORD WINAPI GetProcessId(HANDLE);
API DWORD WINAPI GetThreadId(HANDLE);
API BOOL WINAPI GetExitCodeProcess(HANDLE,DWORD*);
API BOOL WINAPI GetExitCodeThread(HANDLE,DWORD*);
API DWORD WINAPI SetFilePointer(HANDLE,long,long*,DWORD);
API BOOL WINAPI SetFilePointerEx(HANDLE,long long,long long*,DWORD);
API BOOL WINAPI GetFileSizeEx(HANDLE,long long*);
API BOOL WINAPI SetEndOfFile(HANDLE);
API BOOL WINAPI GetFileTime(HANDLE,FILETIME*,FILETIME*,FILETIME*);
API BOOL WINAPI SetFileTime(HANDLE,const FILETIME*,const FILETIME*,const FILETIME*);
API BOOL WINAPI GetFileInformationByHandle(HANDLE,BY_HANDLE_FILE_INFORMATION*);
API BOOL WINAPI GetFileInformationByHandleEx(HANDLE,DWORD,void*,DWORD);
API DWORD WINAPI GetFinalPathNameByHandleA(HANDLE,char*,DWORD,DWORD);
API DWORD WINAPI GetFinalPathNameByHandleW(HANDLE,WORD*,DWORD,DWORD);
API BOOL WINAPI SetFileInformationByHandle(HANDLE,DWORD,const void*,DWORD);
API BOOL WINAPI SetFileAttributesA(const char*,DWORD);
API BOOL WINAPI SetFileAttributesW(const WORD*,DWORD);
API DWORD WINAPI GetFileAttributesA(const char*);
API DWORD WINAPI GetLastError(void);
API void WINAPI SetLastError(DWORD);
API DWORD WINAPI TlsAlloc(void);
API BOOL WINAPI TlsFree(DWORD);
API BOOL WINAPI TlsSetValue(DWORD,void*);
API void* WINAPI TlsGetValue(DWORD);
API void* WINAPI TlsGetValue2(DWORD);
typedef BOOL (WINAPI *INITONCEPROC)(DWORD*,void*,void**);
API void WINAPI InitOnceInitialize(DWORD*);
API BOOL WINAPI InitOnceBeginInitialize(DWORD*,DWORD,BOOL*,void**);
API BOOL WINAPI InitOnceComplete(DWORD*,DWORD,void*);
API BOOL WINAPI InitOnceExecuteOnce(DWORD*,INITONCEPROC,void*,void**);
API BOOL WINAPI WaitOnAddress(volatile void*,void*,DWORD,DWORD);
API void WINAPI WakeByAddressSingle(void*);
API void WINAPI WakeByAddressAll(void*);
typedef struct {DWORD debug;long lockCount,recursion;HANDLE owner,semaphore;DWORD spin;} CRITICAL_SECTION;
API void WINAPI InitializeCriticalSection(CRITICAL_SECTION*);
API BOOL WINAPI InitializeCriticalSectionAndSpinCount(CRITICAL_SECTION*,DWORD);
API BOOL WINAPI InitializeCriticalSectionEx(CRITICAL_SECTION*,DWORD,DWORD);
API DWORD WINAPI SetCriticalSectionSpinCount(CRITICAL_SECTION*,DWORD);
API void WINAPI EnterCriticalSection(CRITICAL_SECTION*);
API BOOL WINAPI TryEnterCriticalSection(CRITICAL_SECTION*);
API void WINAPI LeaveCriticalSection(CRITICAL_SECTION*);
API void WINAPI DeleteCriticalSection(CRITICAL_SECTION*);
API BOOL WINAPI SetEnvironmentVariableA(const char*,const char*);
API DWORD WINAPI GetEnvironmentVariableA(const char*,char*,DWORD);
API DWORD WINAPI ExpandEnvironmentStringsA(const char*,char*,DWORD);
API char* WINAPI GetEnvironmentStrings(void);
API BOOL WINAPI FreeEnvironmentStringsA(char*);
API WORD* WINAPI GetEnvironmentStringsW(void);
API BOOL WINAPI FreeEnvironmentStringsW(WORD*);
API DWORD WINAPI GetCurrentDirectoryA(DWORD,char*);
API HANDLE WINAPI GetModuleHandleA(const char*);
API HANDLE WINAPI LoadLibraryA(const char*);
API void* WINAPI GetProcAddress(HANDLE,const char*);
API DWORD WINAPI GetTickCount(void);
API HANDLE WINAPI CreateThread(void*,DWORD,void*,void*,DWORD,DWORD*);
API HANDLE WINAPI CreateEventA(void*,BOOL,BOOL,const char*);
API HANDLE WINAPI CreateEventW(void*,BOOL,BOOL,const WORD*);
API HANDLE WINAPI CreateMutexA(void*,BOOL,const char*);
API HANDLE WINAPI CreateMutexW(void*,BOOL,const WORD*);
API HANDLE WINAPI CreateSemaphoreA(void*,long,long,const char*);
API HANDLE WINAPI CreateSemaphoreW(void*,long,long,const WORD*);
API HANDLE WINAPI OpenEventA(DWORD,BOOL,const char*);
API HANDLE WINAPI OpenEventW(DWORD,BOOL,const WORD*);
API HANDLE WINAPI OpenMutexA(DWORD,BOOL,const char*);
API HANDLE WINAPI OpenMutexW(DWORD,BOOL,const WORD*);
API HANDLE WINAPI OpenSemaphoreA(DWORD,BOOL,const char*);
API HANDLE WINAPI OpenSemaphoreW(DWORD,BOOL,const WORD*);
API HANDLE WINAPI CreateEventExA(void*,const char*,DWORD,DWORD);
API HANDLE WINAPI CreateEventExW(void*,const WORD*,DWORD,DWORD);
API HANDLE WINAPI CreateMutexExA(void*,const char*,DWORD,DWORD);
API HANDLE WINAPI CreateMutexExW(void*,const WORD*,DWORD,DWORD);
API HANDLE WINAPI CreateSemaphoreExA(void*,long,long,const char*,DWORD,DWORD);
API HANDLE WINAPI CreateSemaphoreExW(void*,long,long,const WORD*,DWORD,DWORD);
API BOOL WINAPI SetEvent(HANDLE);
API BOOL WINAPI ResetEvent(HANDLE);
API BOOL WINAPI ReleaseMutex(HANDLE);
API BOOL WINAPI ReleaseSemaphore(HANDLE,long,long*);
API DWORD WINAPI WaitForSingleObject(HANDLE,DWORD);
API DWORD WINAPI WaitForSingleObjectEx(HANDLE,DWORD,BOOL);
API DWORD WINAPI WaitForMultipleObjects(DWORD,const HANDLE*,BOOL,DWORD);
API DWORD WINAPI WaitForMultipleObjectsEx(DWORD,const HANDLE*,BOOL,DWORD,BOOL);
API WORD WINAPI RegisterClassA(const WNDCLASSA*);
API WORD WINAPI RegisterClassW(const WNDCLASSW*);
API BOOL WINAPI UnregisterClassA(const char*,HANDLE);
API BOOL WINAPI UnregisterClassW(const WORD*,HANDLE);
API DWORD WINAPI GetClassLongA(HWND,int);
API DWORD WINAPI GetClassLongW(HWND,int);
API DWORD WINAPI SetClassLongA(HWND,int,long);
API DWORD WINAPI SetClassLongW(HWND,int,long);
API long WINAPI GetWindowLongA(HWND,int);
API long WINAPI GetWindowLongW(HWND,int);
API long WINAPI SetWindowLongA(HWND,int,long);
API long WINAPI SetWindowLongW(HWND,int,long);
API HWND WINAPI CreateWindowExW(DWORD,const WORD*,const WORD*,DWORD,int,int,int,int,HWND,HANDLE,HANDLE,void*);
API HWND WINAPI CreateWindowExA(DWORD,const char*,const char*,DWORD,int,int,int,int,HWND,HANDLE,HANDLE,void*);
API BOOL WINAPI ShowWindow(HWND,int);
API BOOL WINAPI UpdateWindow(HWND);
API BOOL WINAPI GetMessageA(MSG*,HWND,DWORD,DWORD);
API BOOL WINAPI TranslateMessage(const MSG*);
API long WINAPI DispatchMessageA(const MSG*);
API long WINAPI DefWindowProcA(HWND,DWORD,DWORD,long);
API void WINAPI PostQuitMessage(int);
API BOOL WINAPI DestroyWindow(HWND);
API HDC WINAPI BeginPaint(HWND,PAINTSTRUCT*);
API BOOL WINAPI EndPaint(HWND,const PAINTSTRUCT*);
API BOOL WINAPI SetWindowTextA(HWND,const char*);
API BOOL WINAPI SetWindowTextW(HWND,const WORD*);
API int WINAPI GetWindowTextA(HWND,char*,int);
API int WINAPI GetWindowTextW(HWND,WORD*,int);
API int WINAPI GetWindowTextLengthA(HWND);
API int WINAPI GetWindowTextLengthW(HWND);
API long WINAPI SendMessageA(HWND,DWORD,DWORD,long);
API long WINAPI SendMessageW(HWND,DWORD,DWORD,long);
API int WINAPI MessageBoxA(HWND,const char*,const char*,DWORD);
API BOOL WINAPI InvalidateRect(HWND,const RECT*,BOOL);
API DWORD WINAPI SetTimer(HWND,DWORD,DWORD,void*);
API BOOL WINAPI KillTimer(HWND,DWORD);
API BOOL WINAPI TextOutA(HDC,int,int,const char*,int);
API DWORD WINAPI SetTextColor(HDC,DWORD);
API int WINAPI SetBkMode(HDC,int);
API DWORD WINAPI SetBkColor(HDC,DWORD);
API HANDLE WINAPI CreateSolidBrush(DWORD);
API HANDLE WINAPI ExtCreatePen(DWORD,DWORD,const void*,DWORD,const DWORD*);
API HANDLE WINAPI CreatePen(int,int,DWORD);
API HANDLE WINAPI CreatePenIndirect(const void*);
API HANDLE WINAPI CreateBrushIndirect(const void*);
API HANDLE WINAPI SelectObject(HDC,HANDLE);
API BOOL WINAPI DeleteObject(HANDLE);
API HANDLE WINAPI GetStockObject(int);
API BOOL WINAPI Rectangle(HDC,int,int,int,int);
API BOOL WINAPI Ellipse(HDC,int,int,int,int);
API BOOL WINAPI MoveToEx(HDC,int,int,void*);
API BOOL WINAPI LineTo(HDC,int,int);
API int WINAPI FillRect(HDC,const RECT*,HANDLE);
API int WINAPI FrameRect(HDC,const RECT*,HANDLE);
API int WINAPI StretchDIBits(HDC,int,int,int,int,int,int,int,int,const void*,const void*,DWORD,DWORD);
API int __cdecl printf(const char*,...);
API int __cdecl sprintf(char*,const char*,...);
API int __cdecl puts(const char*);
API void* __cdecl memset(void*,int,unsigned int);
#define RGB(r,g,b) ((DWORD)((r)|((g)<<8)|((b)<<16)))
#define GENERIC_READ 0x80000000U
#define GENERIC_WRITE 0x40000000U
#define INVALID_HANDLE ((HANDLE)0xFFFFFFFFU)
#define WM_DESTROY 2
#define WM_PAINT 15
#define WM_COMMAND 0x111
#define WM_TIMER 0x113
#define WS_OVERLAPPEDWINDOW 0x00CF0000U
#define WS_CHILD_VISIBLE 0x50000000U
API void WINAPI InitializeSRWLock(void*);
API void WINAPI InitializeConditionVariable(void*);
API BOOL WINAPI SleepConditionVariableCS(void*,void*,DWORD);
API BOOL WINAPI SleepConditionVariableSRW(void*,void*,DWORD,DWORD);
API void WINAPI WakeConditionVariable(void*);
API void WINAPI WakeAllConditionVariable(void*);
API void WINAPI AcquireSRWLockShared(void*);
API void WINAPI AcquireSRWLockExclusive(void*);
API BYTE WINAPI TryAcquireSRWLockShared(void*);
API BYTE WINAPI TryAcquireSRWLockExclusive(void*);
API void WINAPI ReleaseSRWLockShared(void*);
API void WINAPI ReleaseSRWLockExclusive(void*);
API BOOL WINAPI GetClientRect(HWND,RECT*);
API BOOL WINAPI GetWindowRect(HWND,RECT*);
API BOOL WINAPI IsWindow(HWND);
API HWND WINAPI GetParent(HWND);
API BOOL WINAPI IsChild(HWND,HWND);
API BOOL WINAPI EnableWindow(HWND,BOOL);
API BOOL WINAPI IsWindowEnabled(HWND);
API BOOL WINAPI IsWindowVisible(HWND);
API HWND WINAPI SetFocus(HWND);
API HWND WINAPI GetFocus(void);
API BOOL WINAPI SetPropA(HWND,const char*,HANDLE);
API BOOL WINAPI SetPropW(HWND,const WORD*,HANDLE);
API HANDLE WINAPI GetPropA(HWND,const char*);
API HANDLE WINAPI GetPropW(HWND,const WORD*);
API HANDLE WINAPI RemovePropA(HWND,const char*);
API HANDLE WINAPI RemovePropW(HWND,const WORD*);
API int WINAPI EnumPropsA(HWND,BOOL (WINAPI *)(HWND,char*,HANDLE));
API int WINAPI EnumPropsW(HWND,BOOL (WINAPI *)(HWND,WORD*,HANDLE));
API int WINAPI EnumPropsExA(HWND,BOOL (WINAPI *)(HWND,char*,HANDLE,DWORD),DWORD);
API int WINAPI EnumPropsExW(HWND,BOOL (WINAPI *)(HWND,WORD*,HANDLE,DWORD),DWORD);
API WORD WINAPI AddAtomA(const char*);
API WORD WINAPI AddAtomW(const WORD*);
API WORD WINAPI FindAtomA(const char*);
API WORD WINAPI FindAtomW(const WORD*);
API WORD WINAPI DeleteAtom(WORD);
API DWORD WINAPI GetAtomNameA(WORD,char*,int);
API DWORD WINAPI GetAtomNameW(WORD,WORD*,int);
API BOOL WINAPI InitAtomTable(DWORD);
API WORD WINAPI GlobalAddAtomA(const char*);
API WORD WINAPI GlobalAddAtomW(const WORD*);
API WORD WINAPI GlobalFindAtomA(const char*);
API WORD WINAPI GlobalFindAtomW(const WORD*);
API WORD WINAPI GlobalDeleteAtom(WORD);
API DWORD WINAPI GlobalGetAtomNameA(WORD,char*,int);
API DWORD WINAPI GlobalGetAtomNameW(WORD,WORD*,int);
API WORD WINAPI GlobalAddAtomExA(const char*,DWORD);
API WORD WINAPI GlobalAddAtomExW(const WORD*,DWORD);
API BOOL WINAPI IsWindowUnicode(HWND);
API DWORD WINAPI GetWindowThreadProcessId(HWND,DWORD*);
API DWORD WINAPI GetCurrentThreadId(void);
API DWORD WINAPI GetCurrentProcessId(void);
#endif
