"""Record Windows 1252/437 conversion tables using only owned scalar buffers."""
import ctypes
import json
import pathlib
import sys

root=pathlib.Path(__file__).resolve().parent.parent
k=ctypes.WinDLL('kernel32',use_last_error=True)
mb=k.MultiByteToWideChar
mb.argtypes=[ctypes.c_uint,ctypes.c_uint,ctypes.c_void_p,ctypes.c_int,ctypes.c_void_p,ctypes.c_int]
wc=k.WideCharToMultiByte
wc.argtypes=[ctypes.c_uint,ctypes.c_uint,ctypes.c_void_p,ctypes.c_int,ctypes.c_void_p,ctypes.c_int,ctypes.c_void_p,ctypes.POINTER(ctypes.c_int)]
tables={}
for cp in [1252,437]:
    decode={}
    for flags in [0,2,4,6,8,10,12,14]:
        row=[]
        for byte in range(256):
            src=ctypes.c_ubyte(byte);out=(ctypes.c_ushort*8)()
            count=mb(cp,flags,ctypes.byref(src),1,out,8)
            if not count and ctypes.get_last_error()!=1113:raise RuntimeError('Unexpected decoding error')
            row.append(list(out)[:count] if count else None)
        decode[flags]=row
    encode={}
    for flags in [0,1024]:
        row=[]
        for unit in range(65536):
            src=ctypes.c_ushort(unit);out=ctypes.c_ubyte();used=ctypes.c_int()
            if wc(cp,flags,ctypes.byref(src),1,ctypes.byref(out),1,None,ctypes.byref(used))!=1:raise RuntimeError('Unexpected encoding error')
            if not used.value:row.append([unit,out.value])
        encode[flags]=row
    tables[cp]={'decode':decode,'encode':encode}
version=sys.getwindowsversion()
header=f'// Native Windows {version.major}.{version.minor}.{version.build}; generated by tools/build-sbcs-tables.py.\n'
text=header+'export const sbcsTables='+json.dumps(tables,separators=(',', ':'))+';\n'
(root/'src/runtime/sbcs-tables.js').write_text(text,encoding='utf8')
print('Recorded all byte decodings and 65536 UTF-16 unit encodings for both code pages and conversion modes.')
