"""Record Windows BMP uppercase mappings and verify them with CompareStringOrdinal.

Run on Windows with Python. Calls only host APIs on owned scalar/string data;
does not execute guest programs. The generated module is used in all hosts.
"""
import ctypes
import json
import pathlib
import random
import sys

root = pathlib.Path(__file__).resolve().parent.parent
up = ctypes.WinDLL('ntdll').RtlUpcaseUnicodeChar
up.argtypes = [ctypes.c_ushort]
up.restype = ctypes.c_ushort
compare = ctypes.WinDLL('kernel32').CompareStringOrdinal
compare.argtypes = [ctypes.c_wchar_p, ctypes.c_int, ctypes.c_wchar_p, ctypes.c_int, ctypes.c_int]
pairs = []
for char in range(65536):
    upper = up(char)
    if char != upper:
        if compare(chr(char), 1, chr(upper), 1, 1) != 2:
            raise RuntimeError(f'Ordinal mapping mismatch at U+{char:04X}')
        pairs.append([char, upper])
version = sys.getwindowsversion()
header = (f'// Observed Windows {version.major}.{version.minor}.{version.build} BMP uppercase mappings.\n'
          '// Generated by tools/build-ordinal-table.py; each mapping checked with CompareStringOrdinal.\n')
rows = [','.join(json.dumps(pair, separators=(',', ':')) for pair in pairs[i:i+12]) for i in range(0, len(pairs), 12)]
(root / 'src/runtime/ordinal-table.js').write_text(header + 'export const ordinalUpper=new Map([\n' + ',\n'.join(rows) + '\n]);\n', encoding='utf-8')
print(f'Verified {len(pairs)} nonidentity mappings across all 65536 UTF-16 code units.')
rng=random.Random(8601)
vectors=[]
for i in range(256):
    left=[rng.randrange(65536) for _ in range(rng.randrange(1,9))]
    right=list(left)
    if i%3==0:
        left[rng.randrange(len(left))]=pairs[rng.randrange(len(pairs))][0]
        right=[up(c) for c in left]
    elif i%3==1:
        right[rng.randrange(len(right))]=rng.randrange(65536)
    else:
        right=right[:-1]
    a=''.join(map(chr,left));b=''.join(map(chr,right))
    for ignore in [0,1]:
        result=compare(a,len(left),b,len(right),ignore)
        vectors.append([left,right,ignore,result])
(root/'tests/ordinal-native-vectors.json').write_text(json.dumps(vectors,separators=(',', ':'))+'\n',encoding='utf-8')
print(f'Recorded {len(vectors)} seeded native comparison vectors.')
