"""Record Windows GetStringTypeW classifications for every UTF-16 code unit."""
import ctypes
import hashlib
import json
import pathlib
import sys

root=pathlib.Path(__file__).resolve().parent.parent
f=ctypes.WinDLL('kernel32').GetStringTypeW
f.argtypes=[ctypes.c_uint,ctypes.c_void_p,ctypes.c_int,ctypes.c_void_p]
source=(ctypes.c_ushort*65536)(*range(65536))
ranges={};digests={}
for mode in [1,2,4]:
    output=(ctypes.c_ushort*65536)()
    if not f(mode,source,65536,output):raise RuntimeError('GetStringTypeW failed')
    digests[mode]=hashlib.sha256(bytes(output)).hexdigest()
    row=[];start=0
    for i in range(1,65537):
        if i==65536 or output[i]!=output[start]:
            row.append([start,i,output[start]]);start=i
    ranges[mode]=row
v=sys.getwindowsversion()
header=f'// Windows {v.major}.{v.minor}.{v.build}; generated by tools/build-character-types.py.\n'
(root/'src/runtime/character-type-table.js').write_text(header+'export const characterTypeRanges='+json.dumps(ranges,separators=(',', ':'))+';\n',encoding='utf8')
(root/'tests/character-type-native-hashes.json').write_text(json.dumps(digests,indent=2)+'\n',encoding='utf8')
print('Recorded 196608 native classifications, range-compressed tables and independent output hashes.')
