import {PackageStore} from './store.js';
import {GuestDisplay} from './ui/display.js';
import {VirtualFileSystem} from './runtime/vfs.js';
import {exportPackage} from './backup.js';
const $=id=>document.getElementById(id),store=new PackageStore();
let current=null,selected=null,worker=null,state='idle',debug=null,lastFault=null,importing=false,preview=null,folder='C:/',saveChain=Promise.resolve(),catalog=new Set(),exportPending=false,toastTimer=null,stopTimer=null,packageList=[];
const display=new GuestDisplay($('desktop'),event=>worker?.postMessage({type:'input',event}));
const active=()=>['loading','running','paused','stopping'].includes(state);
const bytes=n=>n>=1048576?(n/1048576).toFixed(1)+' MiB':n>=1024?(n/1024).toFixed(1)+' KiB':n+' B';
function toast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,7000);}
function log(text,level='system'){const terminal=$('terminal'),nearBottom=terminal.scrollHeight-terminal.scrollTop-terminal.clientHeight<70,line=document.createElement('div');line.className='log-line '+level;line.textContent=text;terminal.append(line);while(terminal.childNodes.length>1500||terminal.textContent.length>1024*1024)terminal.firstChild?.remove();if(nearBottom)terminal.scrollTop=terminal.scrollHeight;}
function controls(){const running=active();$('run').disabled=!selected?.runnable||running||importing;$('run').title=selected&&!selected.runnable?selected.reason:'';$('pause').disabled=!['running','paused'].includes(state);$('pause').textContent=state==='paused'?'▶ Resume':'Ⅱ Pause';$('step').disabled=state!=='paused';$('stop').disabled=!running||state==='stopping';$('console-input').disabled=!['running','paused'].includes(state);$('console-send').disabled=$('console-input').disabled;$('dropzone').disabled=running||importing;$('load-demo').disabled=running||importing;$('package-select').disabled=running||importing;$('delete-package').disabled=!current||running||importing;$('export-zip').disabled=!current||importing||state==='loading'||exportPending;}
function status(next,label=null){state=next;$('status').dataset.state=next;const names={idle:'Ready',loading:'Loading',running:'Running',paused:'Paused',exited:'Exited',fault:'Stopped · fault',stopped:'Stopped',stopping:'Stopping'};$('status').lastChild.textContent=' '+(label||names[next]||next);controls();}
function tab(name){for(const b of document.querySelectorAll('[data-tab]')){const yes=b.dataset.tab===name;b.classList.toggle('active',yes);b.setAttribute('aria-selected',String(yes));}for(const p of document.querySelectorAll('.tab-panel'))p.hidden=p.id!=='tab-'+name;if(name==='debugger')worker?.postMessage({type:'debug'});if(name==='files')renderFiles();}
function canonical(dll){dll=dll.toLowerCase();if(dll==='kernelbase.dll'||dll.startsWith('api-ms-win-core-'))return 'kernel32.dll';if(dll==='ucrtbase.dll'||dll.startsWith('api-ms-win-crt-'))return 'msvcrt.dll';return dll;}
function supported(dll,name){return catalog.has(canonical(dll)+'!'+name);}
function selectExe(path){selected=current?.executables.find(e=>e.path===path)||null;if(current){current.selected=path;queueSave(current);}renderExecutables();renderCompatibility();controls();}
function renderExecutables(){const list=$('exe-list');list.replaceChildren();$('exe-count').textContent=current?.executables.length||0;if(!current?.executables.length){const text=document.createElement('div');text.className='empty-list';text.textContent=current?'No .exe files were found in this ZIP. The virtual disk can still be inspected and exported.':'Import a ZIP to inspect its executables.';list.append(text);return;}
  for(const exe of current.executables){const button=document.createElement('button');button.type='button';button.className='exe-option'+(selected?.path===exe.path?' selected':'')+(!exe.runnable?' unsupported':'');const icon=document.createElement('span');icon.className='exe-icon';icon.textContent=exe.architecture==='x86'?'32':'!';const info=document.createElement('span');info.className='exe-info';const name=document.createElement('strong');name.textContent=exe.path.split('/').at(-1);const sub=document.createElement('small');sub.textContent=exe.runnable?exe.architecture+' · '+exe.subsystem:exe.architecture+' · not supported';info.append(name,sub);button.append(icon,info);button.title=exe.path+'\n'+(exe.reason||'');button.disabled=active();button.addEventListener('click',()=>selectExe(exe.path));list.append(button);}
}
function renderCompatibility(){const root=$('imports');root.replaceChildren();if(!selected){$('compat-summary').textContent='Select an executable to inspect its architecture and import table.';return;}const groups=selected.imports||[],total=groups.reduce((n,g)=>n+g.symbols.length,0),known=groups.reduce((n,g)=>n+g.symbols.filter(s=>supported(g.dll,s)).length,0);$('compat-summary').textContent=(selected.runnable?'32-bit PE candidate — execution is not guaranteed.':selected.reason)+'\n'+total+' imported symbols · '+known+' built-in handlers · '+(total-known)+' require packaged DLL resolution or are unsupported.\n'+selected.path+(selected.delayImports?'\nDelay imports detected: this build will reject them.':'');
  for(const group of groups){const section=document.createElement('section');section.className='import-group';const h=document.createElement('h4');h.textContent=group.dll;section.append(h);for(const name of group.symbols){const span=document.createElement('span'),yes=supported(group.dll,name);span.className='import-symbol'+(yes?'':' missing');span.textContent=typeof name==='number'?'ordinal #'+name:name;span.title=yes?'Handler exists; its supported arguments and semantics may be limited.':'No built-in handler. A packaged application DLL may supply this export; otherwise it will fault if called.';section.append(span);}root.append(section);}
}
async function refreshLibrary(){try{packageList=await store.list();const select=$('package-select');select.replaceChildren();if(!packageList.length){const op=document.createElement('option');op.textContent='No packages imported';op.value='';select.append(op);}for(const pkg of packageList){const op=document.createElement('option');op.value=pkg.id;op.textContent=pkg.name;select.append(op);}select.value=current?.id||'';$('package-count').textContent=packageList.length;}catch(e){toast('Browser storage unavailable: '+e.message,true);}}
function queueSave(pkg){const reference=pkg;$('save-state').textContent='Saving virtual disk…';saveChain=saveChain.catch(()=>{}).then(async()=>{reference.updated=Date.now();await store.put(reference);if(current?.id===reference.id)$('save-state').textContent='Saved locally · '+new Date().toLocaleTimeString();}).catch(e=>{$('save-state').textContent='Not saved: '+e.message;toast('Could not persist the virtual disk. Export a backup before leaving.',true);throw e;});return saveChain;}
async function mount(pkg){if(active())return;worker?.terminate();worker=null;display.reset();$('desktop-empty').hidden=false;current=pkg;folder='C:/';preview=null;debug=null;lastFault=null;selected=pkg.executables.find(e=>e.path===pkg.selected)||pkg.executables.find(e=>e.runnable)||pkg.executables[0]||null;pkg.selected=selected?.path||'';$('args').value=pkg.args||'';$('workspace-title').textContent=pkg.name;$('save-state').textContent='Restored local virtual disk';status('idle');renderExecutables();renderCompatibility();renderFiles();try{localStorage.setItem('browser86-last-package',pkg.id);}catch{}await refreshLibrary();}
async function importZip(file){if(active()){toast('Stop the running application before importing another package.',true);return;}if(importing)return;if(file.size>256*1024*1024){toast('ZIP exceeds the 256 MiB archive limit.',true);return;}importing=true;controls();$('progress-area').hidden=false;$('progress-text').textContent='Reading '+file.name+'…';$('progress-fill').style.width='2%';let importer;
  try{const buffer=await file.arrayBuffer(),hash=new Uint8Array(await crypto.subtle.digest('SHA-256',buffer)),id=Array.from(hash,b=>b.toString(16).padStart(2,'0')).join('');let old=null;try{old=await store.get(id);}catch(e){log('Persistence unavailable: '+e.message,'warning');}if(old){await mount(old);toast('Restored the saved virtual disk for this ZIP.');return;}
    importer=new Worker(new URL('./import-worker.js',import.meta.url),{type:'module'});
    const result=await new Promise((resolve,reject)=>{importer.onmessage=event=>{const msg=event.data;if(msg.type==='progress'){$('progress-fill').style.width=(5+msg.completed/Math.max(1,msg.entries)*95)+'%';$('progress-text').textContent=msg.completed+'/'+msg.entries+' · '+msg.path;}else if(msg.type==='complete')resolve(msg);else if(msg.type==='error')reject(new Error(msg.code+': '+msg.message));};importer.onerror=e=>reject(new Error(e.message||'ZIP import worker failed.'));importer.postMessage({buffer},[buffer]);});
    const vfs=new VirtualFileSystem(result.entries);const pkg={id,name:result.manifest?.name||file.name,selected:result.manifest?.selected||result.executables.find(e=>e.runnable)?.path||'',args:result.manifest?.args||'',entries:vfs.snapshot(),executables:result.executables,updated:Date.now()};await queueSave(pkg).catch(()=>{});await mount(pkg);log('Mounted '+file.name+': '+result.executables.length+' executable(s), '+vfs.metadata().filter(e=>!e.directory).length+' files.');toast('ZIP imported. Choose an executable and press Run.');
  }catch(e){toast(e.message,true);log(e.message,'error');}finally{importer?.terminate();importing=false;$('progress-area').hidden=true;$('zip-input').value='';controls();}}
function snapshotReceived(msg,reference,origin){reference.entries=msg.entries;reference.updated=Date.now();const save=queueSave(reference);save.catch(()=>{}).finally(()=>origin.postMessage({type:'saved'}));if(current?.id===reference.id){renderFiles();if(exportPending){exportPending=false;doExport(reference);controls();}}}
async function run(){if(!current||!selected?.runnable||active())return;await saveChain.catch(()=>{});current.args=$('args').value;current.selected=selected.path;queueSave(current).catch(()=>{});worker?.terminate();display.reset();$('desktop-empty').hidden=false;$('terminal').replaceChildren();debug=null;lastFault=null;status('loading');renderExecutables();$('workspace-title').textContent=selected.path.split('/').at(-1);$('metric-detail').textContent='Mapping executable and linking imports';for(const id of ['metric-instructions','metric-apis','metric-memory'])$(id).textContent='—';
  log('Launching '+selected.path+'\nRuntime: original IA-32 interpreter / custom Win32 handlers.');
  const reference=current,origin=new Worker(new URL('./runtime-worker.js',import.meta.url),{type:'module'});worker=origin;
  origin.onmessage=event=>{const msg=event.data;if(msg.type==='snapshot'){snapshotReceived(msg,reference,origin);return;}if(worker!==origin)return;switch(msg.type){
    case 'module':log('Mapped '+msg.path+' at '+msg.base+' ('+bytes(msg.bytes)+')');break;
    case 'loaded':status('running');renderExecutables();log('Entrypoint loaded. Working directory: '+msg.cwd);if(msg.missing.length)log(msg.missing.length+' unresolved import(s). Execution stops only if an unresolved import is called.','warning');break;
    case 'stdout':log(msg.text,msg.stream||'stdout');break;
    case 'log':log(msg.message,msg.level);break;
    case 'window':display.window(msg);break;
    case 'drawBatch':display.draw(msg.commands);break;
    case 'dialog':display.dialog(msg);break;
    case 'title':$('workspace-title').textContent=msg.text;break;
    case 'waiting':$('metric-detail').textContent=msg.reason;break;
    case 'status':status(msg.status);if(msg.reason)log(msg.reason);if(msg.status==='stopped')clearTimeout(stopTimer);renderExecutables();break;
    case 'stats':$('metric-instructions').textContent=msg.instructions.toLocaleString();$('metric-apis').textContent=msg.apiCalls.toLocaleString();$('metric-memory').textContent=bytes(msg.committedBytes);if(['running','paused'].includes(state))$('metric-detail').textContent=msg.waiting||msg.lastApi||msg.status;break;
    case 'exit':status('exited');log('\nProcess exited with code '+msg.code+'. '+msg.instructions.toLocaleString()+' x86 instructions executed.');$('metric-instructions').textContent=msg.instructions.toLocaleString();$('metric-detail').textContent='Exit code '+msg.code;renderExecutables();origin.postMessage({type:'debug'});break;
    case 'fault':lastFault=msg;debug=msg.debug||debug;status('fault');log('\n'+msg.code+'\n'+msg.message,'error');if(msg.detail)log(JSON.stringify(msg.detail,null,2),'debug');$('metric-detail').textContent=msg.code;toast(msg.code+': '+msg.message.slice(0,180),true);renderDebug();renderExecutables();break;
    case 'debug':debug=msg;renderDebug();break;
    case 'files':renderFiles();break;
    case 'file':if(preview?.path===msg.path){preview.data=msg.data;showPreview();}break;
  }};
  origin.onerror=e=>{status('fault');lastFault={code:'WORKER_ERROR',message:e.message};log('Runtime worker error: '+e.message,'error');toast(e.message,true);};
  origin.postMessage({type:'start',entries:current.entries,exePath:selected.path,args:current.args,memoryMiB:Number($('memory').value)});
}
function download(data,name,type='application/octet-stream'){const url=URL.createObjectURL(new Blob([data],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function doExport(pkg){try{download(exportPackage(pkg),pkg.name.replace(/\.zip$/i,'')+'-virtual-disk.zip','application/zip');toast('Virtual disk exported with a restore manifest.');}catch(e){toast('Export failed: '+e.message,true);}}
function renderFiles(){const root=$('file-list');root.replaceChildren();if(!current){$('file-count').textContent='0';return;}const files=current.entries;$('file-count').textContent=files.filter(e=>!e.directory).length;$('file-path').textContent=folder.replaceAll('/','\\');const filter=$('file-search').value.toLowerCase();const prefix=folder.replace(/\/$/,'')+'/';const entries=files.filter(e=>e.path!==folder&&(filter?e.path.toLowerCase().includes(filter):e.path.toLowerCase().startsWith(prefix.toLowerCase())&&!e.path.slice(prefix.length).includes('/'))).sort((a,b)=>Number(b.directory)-Number(a.directory)||a.path.localeCompare(b.path));
  if(folder!=='C:/'&&!filter){const up=document.createElement('button');up.className='file-row';up.textContent='↰  ..';up.onclick=()=>{folder=folder.slice(0,folder.lastIndexOf('/'))||'C:/';if(folder==='C:')folder='C:/';renderFiles();};root.append(up);}
  for(const entry of entries){const row=document.createElement('button');row.className='file-row'+(preview?.path===entry.path?' selected':'');const icon=document.createElement('span');icon.className='file-icon';icon.textContent=entry.directory?'▸':'·';const name=document.createElement('span');name.className='file-label';name.textContent=filter?entry.path:entry.path.slice(prefix.length);const size=document.createElement('span');size.className='file-size';size.textContent=entry.directory?'DIR':bytes(entry.data?.length||0);row.append(icon,name,size);row.title=entry.path;row.onclick=()=>{if(entry.directory){folder=entry.path;renderFiles();}else{preview={path:entry.path,data:entry.data};showPreview();renderFiles();if(active())worker?.postMessage({type:'readFile',path:entry.path});}};root.append(row);}
  if(!entries.length){const empty=document.createElement('p');empty.className='muted';empty.textContent='No matching files.';root.append(empty);}}
function showPreview(){if(!preview)return;$('preview-name').textContent=preview.path.split('/').at(-1);$('download-file').disabled=false;const data=new Uint8Array(preview.data||[]),sample=data.subarray(0,65536);const likelyText=!sample.subarray(0,4096).some(b=>b===0||b<9||b>13&&b<32);if(likelyText)$('preview-content').textContent=new TextDecoder().decode(sample)+(data.length>sample.length?'\n… Preview truncated.':'');else{const rows=[];for(let i=0;i<Math.min(512,data.length);i+=16){const slice=data.subarray(i,i+16);rows.push(i.toString(16).padStart(8,'0')+'  '+Array.from(slice,b=>b.toString(16).padStart(2,'0')).join(' ').padEnd(47)+'  '+Array.from(slice,b=>b>=32&&b<127?String.fromCharCode(b):'.').join(''));}$('preview-content').textContent=bytes(data.length)+' · binary\n\n'+rows.join('\n')+(data.length>512?'\n…':'');}}
function renderDebug(){const regs=$('registers');regs.replaceChildren();if(!debug)return;for(const [name,value]of Object.entries({...debug.registers,EIP:debug.eip,EFLAGS:debug.flags})){const box=document.createElement('div');box.className='register';const label=document.createElement('span');label.textContent=name;const val=document.createElement('strong');val.textContent=value||'—';box.append(label,val);regs.append(box);}$('api-trace').textContent=(debug.callTrace||[]).slice().reverse().map(c=>c.caller+'  '+c.api+'\n  '+c.args.join(', ')).join('\n\n')||'No API calls yet.';$('memory-map').textContent=(debug.mappings||[]).map(r=>'0x'+r.start.toString(16).padStart(8,'0')+'–0x'+r.end.toString(16).padStart(8,'0')+' '+r.perm.padEnd(3)+' '+r.label).join('\n')+'\n\nRECENT EIP TRACE\n'+(debug.trace||[]).join(' → ');}
$('dropzone').onclick=()=>$('zip-input').click();$('zip-input').onchange=()=>{const file=$('zip-input').files?.[0];if(file)importZip(file);};
$('load-demo').onclick=async()=>{try{const response=await fetch('demos/browser86-demo.zip');if(!response.ok)throw new Error('Demo package could not be loaded ('+response.status+').');await importZip(new File([await response.blob()],'browser86-demo.zip',{type:'application/zip'}));}catch(e){toast(e.message,true);}};
$('package-select').onchange=async()=>{if(active())return;await saveChain.catch(()=>{});const pkg=await store.get($('package-select').value);if(pkg)await mount(pkg);};
$('run').onclick=()=>run().catch(e=>{status('fault');toast(e.message,true);});
$('pause').onclick=()=>worker?.postMessage({type:state==='paused'?'resume':'pause'});$('step').onclick=()=>worker?.postMessage({type:'step'});
$('stop').onclick=()=>{if(!worker)return;status('stopping');worker.postMessage({type:'stop'});clearTimeout(stopTimer);stopTimer=setTimeout(()=>{if(state==='stopping'&&confirm('The worker is not responding. Force-stop it? Changes since the last received virtual-disk snapshot may be lost.')){worker.terminate();worker=null;status('stopped');renderExecutables();log('Worker force-stopped. The most recent saved virtual disk was retained.','warning');}},3000);};
$('console-form').onsubmit=e=>{e.preventDefault();const text=$('console-input').value;if(!worker||!text)return;log('› '+text,'debug');worker.postMessage({type:'input',event:{kind:'console',text:text.slice(0,65536)}});$('console-input').value='';};$('clear-console').onclick=()=>$('terminal').replaceChildren();
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>tab(button.dataset.tab);
$('export-zip').onclick=()=>{if(!current)return;if(worker&&active()){exportPending=true;controls();worker.postMessage({type:'snapshot'});}else doExport(current);};
$('delete-package').onclick=async()=>{if(!current||active()||!confirm('Delete this saved package and all of its virtual files? Export a virtual-disk backup first to keep them.'))return;await saveChain.catch(()=>{});await store.remove(current.id);current=null;selected=null;worker?.terminate();worker=null;display.reset();$('desktop-empty').hidden=false;status('idle');renderExecutables();renderFiles();renderCompatibility();await refreshLibrary();toast('Saved package deleted.');};
$('file-search').oninput=()=>renderFiles();$('refresh-files').onclick=()=>{if(worker&&active())worker.postMessage({type:'snapshot'});else renderFiles();};$('download-file').onclick=()=>{if(preview)download(preview.data,preview.path.split('/').at(-1));};
$('refresh-debug').onclick=()=>worker?.postMessage({type:'debug'});$('set-breakpoint').onclick=()=>{const value=$('breakpoint').value.trim();if(!/^(?:0x)?[0-9a-f]{1,8}$/i.test(value)){toast('Enter a 32-bit hexadecimal address.',true);return;}const address=parseInt(value.replace(/^0x/i,''),16);worker?.postMessage({type:'breakpoints',addresses:[address]});toast('Breakpoint set at 0x'+address.toString(16).padStart(8,'0'));};$('clear-breakpoint').onclick=()=>{worker?.postMessage({type:'breakpoints',addresses:[]});$('breakpoint').value='';};
$('save-report').onclick=()=>{download(JSON.stringify({runtime:'Browser86',version:'0.1.0',generatedAt:new Date().toISOString(),package:current?.name,executable:selected,state,fault:lastFault,debug},null,2),'browser86-diagnostic.json','application/json');};
let dragDepth=0;window.addEventListener('dragenter',e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();dragDepth++;if(!active())$('global-drop').hidden=false;}});window.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();});window.addEventListener('dragleave',e=>{dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)$('global-drop').hidden=true;});window.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;$('global-drop').hidden=true;const files=[...(e.dataTransfer?.files||[])];if(files.length!==1){toast('Drop one application ZIP at a time.',true);return;}if(!/\.zip$/i.test(files[0].name)){toast('Import the complete application as a ZIP, not a loose executable.',true);return;}importZip(files[0]);});
window.addEventListener('beforeunload',e=>{if(active()){worker?.postMessage({type:'snapshot'});e.preventDefault();e.returnValue='';}});
window.addEventListener('unhandledrejection',e=>{console.error(e.reason);toast(e.reason?.message||String(e.reason),true);});
async function initialize(){if(location.protocol==='file:'){toast('Start the local server with run.cmd or npm start. Browsers cannot load module workers from file://.',true);return;}try{const response=await fetch('src/api-catalog.json');if(response.ok){const records=await response.json();catalog=new Set(records.map(x=>x.dll+'!'+x.name));}}catch{}await refreshLibrary();try{const last=localStorage.getItem('browser86-last-package');if(last){const pkg=await store.get(last);if(pkg)await mount(pkg);}}catch(e){log('Local storage could not be restored: '+e.message,'warning');}controls();}
initialize();
